-- Hyathlon: upper-body rehab frameworks (8), DRAFT for physio review.
-- Adds 24 exercises, 8 rehab programs (24 phases, 149 exercise rows) and 1 guidance item(s).
-- All new programs are review_status 'Draft', so athletes can't see them until approved.
-- Existing running frameworks are not changed, except the shared disclaimer now says "training injuries".
-- Contains no personal data.
set local search_path = public, extensions;


insert into public.exercises (id,name,movement_pattern,equipment,equipment_options,primary_pillar,secondary_pillar,where_setting,best_with,body_region,difficulty,methods,acute_risk) values
('EX0529','Isometric shoulder external rotation','Upper pull','Bodyweight','[["Bodyweight"]]'::jsonb,'Balanced Athleticism',null,'Home or gym','Solo OK','Upper','Beginner',array['Strength','Mobility']::text[],'Low'),
('EX0530','Isometric shoulder abduction','Upper push','Bodyweight','[["Bodyweight"]]'::jsonb,'Balanced Athleticism',null,'Home or gym','Solo OK','Upper','Beginner',array['Strength','Mobility']::text[],'Low'),
('EX0531','Band external rotation','Upper pull','Band','[["Band"]]'::jsonb,'Balanced Athleticism','Durability','Home or gym','Solo OK','Upper','Beginner',array['Strength']::text[],'Low'),
('EX0532','Band internal rotation','Upper push','Band','[["Band"]]'::jsonb,'Balanced Athleticism','Durability','Home or gym','Solo OK','Upper','Beginner',array['Strength']::text[],'Low'),
('EX0533','Side-lying external rotation','Upper pull','Dumbbell','[["Dumbbell"]]'::jsonb,'Balanced Athleticism','Durability','Home or gym','Solo OK','Upper','Beginner',array['Strength']::text[],'Low'),
('EX0534','90/90 band external rotation','Upper pull','Band','[["Band"]]'::jsonb,'Balanced Athleticism','Durability','Home or gym','Solo OK','Upper','Intermediate',array['Strength']::text[],'Low'),
('EX0535','Scaption raise','Upper push','Dumbbell','[["Dumbbell"]]'::jsonb,'Balanced Athleticism','Durability','Home or gym','Solo OK','Upper','Beginner',array['Strength']::text[],'Low'),
('EX0536','Prone Y-T raise','Upper pull','Bodyweight or Dumbbell','[["Bodyweight"], ["Dumbbell"]]'::jsonb,'Balanced Athleticism','Durability','Home or gym','Solo OK','Upper','Beginner',array['Strength']::text[],'Low'),
('EX0537','Ball on wall circles','Upper push','Med ball','[["Med ball"]]'::jsonb,'Balanced Athleticism','Economy','Home or gym','Solo OK','Upper','Beginner',array['Strength','Mobility']::text[],'Low'),
('EX0538','Pendulum swing','Mobility','Bodyweight','[["Bodyweight"]]'::jsonb,'Fatigue Management',null,'Home or gym','Solo OK','Upper','Beginner',array['Mobility']::text[],'Low'),
('EX0539','Supine stick shoulder flexion','Mobility','Bodyweight','[["Bodyweight"]]'::jsonb,'Fatigue Management',null,'Home or gym','Solo OK','Upper','Beginner',array['Mobility']::text[],'Low'),
('EX0540','Isometric elbow flexion hold','Upper pull','Bodyweight','[["Bodyweight"]]'::jsonb,'Balanced Athleticism',null,'Home or gym','Solo OK','Upper','Beginner',array['Strength']::text[],'Low'),
('EX0541','Isometric elbow extension hold','Upper push','Bodyweight','[["Bodyweight"]]'::jsonb,'Balanced Athleticism',null,'Home or gym','Solo OK','Upper','Beginner',array['Strength']::text[],'Low'),
('EX0542','Eccentric biceps curl','Upper pull','Dumbbell','[["Dumbbell"]]'::jsonb,'Balanced Athleticism','Durability','Home or gym','Solo OK','Upper','Beginner',array['Strength']::text[],'Low'),
('EX0543','Isometric wrist extension hold','Carry & grip','Dumbbell','[["Dumbbell"]]'::jsonb,'Durability',null,'Home or gym','Solo OK','Upper','Beginner',array['Strength']::text[],'Low'),
('EX0544','Isometric wrist flexion hold','Carry & grip','Dumbbell','[["Dumbbell"]]'::jsonb,'Durability',null,'Home or gym','Solo OK','Upper','Beginner',array['Strength']::text[],'Low'),
('EX0545','Eccentric wrist extension','Carry & grip','Dumbbell','[["Dumbbell"]]'::jsonb,'Durability',null,'Home or gym','Solo OK','Upper','Beginner',array['Strength']::text[],'Low'),
('EX0546','Eccentric wrist flexion','Carry & grip','Dumbbell','[["Dumbbell"]]'::jsonb,'Durability',null,'Home or gym','Solo OK','Upper','Beginner',array['Strength']::text[],'Low'),
('EX0547','Dumbbell pronation–supination','Carry & grip','Dumbbell','[["Dumbbell"]]'::jsonb,'Durability',null,'Home or gym','Solo OK','Upper','Beginner',array['Strength']::text[],'Low'),
('EX0548','Isometric forearm rotation hold','Carry & grip','Dumbbell','[["Dumbbell"]]'::jsonb,'Durability',null,'Home or gym','Solo OK','Upper','Beginner',array['Strength']::text[],'Low'),
('EX0549','Quadruped wrist rocks','Mobility','Bodyweight','[["Bodyweight"]]'::jsonb,'Durability',null,'Home or gym','Solo OK','Upper','Beginner',array['Mobility']::text[],'Low'),
('EX0550','Push-up on handles','Upper push','Bodyweight','[["Bodyweight"]]'::jsonb,'Balanced Athleticism',null,'Home or gym','Solo OK','Upper','Beginner',array['Strength','Circuit']::text[],'Low'),
('EX0551','Isometric palm press','Upper push','Bodyweight','[["Bodyweight"]]'::jsonb,'Balanced Athleticism',null,'Home or gym','Solo OK','Upper','Beginner',array['Strength']::text[],'Low'),
('EX0552','Band triceps pushdown','Upper push','Band','[["Band"]]'::jsonb,'Balanced Athleticism',null,'Home or gym','Solo OK','Upper','Beginner',array['Strength']::text[],'Low');

-- Shared disclaimer: training injuries
alter table public.rehab_programs alter column disclaimer set default 'Not medical advice. This section shares general considerations and example exercises commonly used for training injuries. It is not a diagnosis or a treatment plan. Always follow the advice of your doctor, physiotherapist or other medical professional, who can assess you individually. If you''re unsure about anything, check with them first.';
update public.rehab_programs set disclaimer = 'Not medical advice. This section shares general considerations and example exercises commonly used for training injuries. It is not a diagnosis or a treatment plan. Always follow the advice of your doctor, physiotherapist or other medical professional, who can assess you individually. If you''re unsure about anything, check with them first.';
update public.rehab_global_guidance set items = array['Not medical advice. This section shares general considerations and example exercises commonly used for training injuries. It is not a diagnosis or a treatment plan. Always follow the advice of your doctor, physiotherapist or other medical professional, who can assess you individually. If you''re unsure about anything, check with them first.']::text[] where key = 'disclaimer';

insert into public.rehab_global_guidance (key,title,items,sort_order) values
('upper_body_control','Shoulder control progression',array['Step 1: quadruped hold (hands under shoulders, push the floor away)','Step 2: plank shoulder taps or reaching from a plank','Step 3: bear crawl, forwards, backwards and sideways','Step 4: bottoms-up kettlebell hold and ball-on-wall circles','Step 5: throws and catches (med ball chest pass, tall-kneeling throws)','Commonly, you start with the better side, progress only once both sides are good, and stop the set when control drops.']::text[],16);

insert into public.rehab_programs (id,name,also_known_as,body_area,overview,red_flags,pain_rule,typical_duration,disclaimer,discharge_criteria,seek_assessment,clinician_required,clinician_notes,physio_review_points,injury_type,review_status) values
('rcrsp','Rotator cuff-related shoulder pain','Rotator cuff tendinopathy / shoulder impingement (subacromial pain)','Shoulder','Pain at the top or side of the shoulder, often felt lifting the arm, reaching overhead or lying on that side. ''Rotator cuff tendinopathy'' and ''impingement'' are now usually grouped under this one label and are commonly managed the same way: settle the irritable movements, rebuild rotator cuff and shoulder blade strength, then return to overhead, pushing and pulling work. Overhead work, high-volume pulling and pressing are common aggravators.',array['Pain after a fall or a sudden pull, especially with new weakness lifting the arm (possible tear)','Can''t lift the arm, or the arm drops when you lower it slowly','Pain or pins and needles spreading below the elbow, or neck pain (possible nerve or neck source)','Constant pain at night or at rest, especially with fever, feeling unwell or unexplained weight loss','A stiff shoulder that is losing movement in every direction (possible frozen shoulder)','A hot, red, swollen joint with fever: seek same-day care']::text[],'A commonly used pain-monitoring guide (confirm with your medical professional): pain up to 3/10 during exercise is usually acceptable if it settles within 24 hours and morning symptoms are no worse the next day. If pain goes above 3/10, or is worse the next morning, a common approach is to drop back to the previous step.','8–12 weeks','Not medical advice. This section shares general considerations and example exercises commonly used for training injuries. It is not a diagnosis or a treatment plan. Always follow the advice of your doctor, physiotherapist or other medical professional, who can assess you individually. If you''re unsure about anything, check with them first.',array['Full, pain-free range overhead and behind the back','External rotation strength within 10% side to side (LSI ≥90%) if it can be measured','Closed-chain shoulder stability test (CKCUEST) or single-arm seated shot put within 10% side to side','Overhead, pushing and pulling exercises at full training volume, pain-free for 2 weeks']::text[],'Consider getting assessed by a physio or doctor if it isn''t clearly improving after 6–8 weeks, or if weakness is getting worse. If you''re unsure, check with your medical professional.',false,'{}'::text[],array['Confirm grouping rotator cuff tendinopathy and impingement into one framework.','Isometrics are included for pain relief as an option only; evidence for them over other exercise is mixed. Keep?','Which discharge tests suit this group (CKCUEST, seated shot put, handheld dynamometry)?']::text[],'Overuse','Draft'),
('biceps_lhb','Biceps tendinopathy (shoulder)','Long head of biceps tendinopathy','Front of shoulder','Pain at the front of the shoulder, often with lifting, pulling or carrying with the arm in front of the body. It often sits alongside rotator cuff-related shoulder pain. Heavy pulling, rowing and carries are common aggravators. The aim is to settle it, then rebuild elbow flexion and shoulder strength progressively.',array['A pop at the elbow crease with bruising, or weakness turning the palm up (possible distal biceps rupture: usually best assessed within days)','A ''Popeye'' bulge in the upper arm after a pop at the front of the shoulder (get it checked)','Clicking or catching deep in the shoulder with pain (possible labral involvement)','Constant pain at night or at rest, especially with fever, feeling unwell or unexplained weight loss','Pins and needles or weakness down the arm','A hot, red, swollen joint with fever: seek same-day care']::text[],'A commonly used pain-monitoring guide (confirm with your medical professional): pain up to 3/10 during exercise is usually acceptable if it settles within 24 hours and morning symptoms are no worse the next day. If pain goes above 3/10, or is worse the next morning, a common approach is to drop back to the previous step.','8–12 weeks','Not medical advice. This section shares general considerations and example exercises commonly used for training injuries. It is not a diagnosis or a treatment plan. Always follow the advice of your doctor, physiotherapist or other medical professional, who can assess you individually. If you''re unsure about anything, check with them first.',array['Biceps curl and hammer curl at pre-injury loads pain-free','Elbow flexion strength within 10% side to side if it can be measured','Heavy pulling, rope pulls and carries at full training loads pain-free for 2 weeks']::text[],'Consider getting assessed by a physio or doctor if there is no clear improvement after 6–8 weeks, or if clicking and catching continue. If you''re unsure, check with your medical professional.',false,'{}'::text[],array['Should this share most of its exercises with the rotator cuff framework?','Is the incline dumbbell curl (lengthened position) appropriate in Phase 3?']::text[],'Overuse','Draft'),
('acj','AC joint sprain','Acromioclavicular joint sprain / irritation','Top of shoulder','Pain on the top of the shoulder where the collarbone meets the shoulder blade, usually after a fall onto the shoulder or an outstretched arm, or irritation from heavy pressing and dips. This framework is for mild sprains after a medical professional has assessed the grade. Moving the arm across the body, dips and bench pressing are usually the last to settle.',array['Visible step or bump at the end of the collarbone, or deformity (higher-grade sprain or fracture: get assessed first)','Can''t lift the arm, or severe pain after a fall','Numbness, tingling or colour change in the arm or hand','Pain over the collarbone itself (possible fracture)','Constant pain at night or at rest, especially with fever, feeling unwell or unexplained weight loss','A hot, red, swollen joint with fever: seek same-day care']::text[],'A commonly used pain-monitoring guide (confirm with your medical professional): in the first phase, keep exercises pain-free or close to it (0–2/10). From Phase 2, pain up to 3/10 is usually acceptable if it settles within 24 hours. Sharp pain, a feeling of weakness or giving way, or new bruising is usually a sign to stop and check with them.','2–8 weeks for mild sprains','Not medical advice. This section shares general considerations and example exercises commonly used for training injuries. It is not a diagnosis or a treatment plan. Always follow the advice of your doctor, physiotherapist or other medical professional, who can assess you individually. If you''re unsure about anything, check with them first.',array['Full, pain-free range including reaching across the body','Push-ups, pressing and dips (if used) at pre-injury loads pain-free','Burpees, pushing, carries and loads on the shoulder at full training volume pain-free']::text[],'Acute injuries are usually best assessed promptly by a doctor or physio, who can grade the sprain. This framework is intended for mild sprains under their guidance. If you''re unsure, check with your medical professional.',true,array['The sprain grade matters: higher grades need medical management and are outside this framework.','The clinician sets when each phase starts; a sling for comfort in the first days is sometimes used.']::text[],array['Confirm this framework is for mild (lower-grade) sprains only, with clinician-set timings.','Carries are held until Phase 3 because hanging weight pulls on the joint. Agree?','When should dips, bench press and burpees be reintroduced?']::text[],'Acute','Draft'),
('elbow_lat','Lateral elbow tendinopathy','Tennis elbow','Outer elbow','Pain on the outside of the elbow, worse with gripping, lifting with the palm down, and carrying. Heavy pulling, rope work, rowing and carries are common aggravators. It can be slow to settle and tends to linger if loaded too hard too soon, so steady, progressive loading of the wrist extensors is the usual approach.',array['Pins and needles or numbness into the hand or fingers','Neck pain or pain spreading from the neck into the arm','A pop or sudden onset with swelling','Elbow locking, or losing the ability to straighten it','Constant pain at night or at rest, especially with fever, feeling unwell or unexplained weight loss','A hot, red, swollen joint with fever: seek same-day care']::text[],'A commonly used pain-monitoring guide (confirm with your medical professional): pain up to 3/10 during exercise is usually acceptable if it settles within 24 hours and morning symptoms are no worse the next day. If pain goes above 3/10, or is worse the next morning, a common approach is to drop back to the previous step.','8–12 weeks (can take longer)','Not medical advice. This section shares general considerations and example exercises commonly used for training injuries. It is not a diagnosis or a treatment plan. Always follow the advice of your doctor, physiotherapist or other medical professional, who can assess you individually. If you''re unsure about anything, check with them first.',array['Pain-free grip strength within 10% side to side (LSI ≥90%) if it can be measured','Reverse wrist curl and wrist roller at a heavy load pain-free','Heavy pulling, rope work and carries at full training loads pain-free for 2 weeks']::text[],'Consider getting assessed by a physio or doctor if there is no clear improvement after 8–12 weeks of consistent loading. If you''re unsure, check with your medical professional.',false,'{}'::text[],array['Is a counterforce brace worth listing as an optional comfort aid?','Elbow tendinopathies can persist for months. Should the timeline be longer by default?']::text[],'Overuse','Draft'),
('elbow_med','Medial elbow tendinopathy','Golfer''s elbow','Inner elbow','Pain on the inside of the elbow, worse with gripping, pulling and turning the palm down. Heavy pulling, rope work, rowing and carries are common aggravators. The approach mirrors tennis elbow, but loads the wrist flexors and forearm rotators instead.',array['Tingling or numbness in the ring and little fingers (possible ulnar nerve involvement)','A pop or sudden pain with bruising on the inner elbow','Elbow locking or losing movement','Constant pain at night or at rest, especially with fever, feeling unwell or unexplained weight loss','A hot, red, swollen joint with fever: seek same-day care']::text[],'A commonly used pain-monitoring guide (confirm with your medical professional): pain up to 3/10 during exercise is usually acceptable if it settles within 24 hours and morning symptoms are no worse the next day. If pain goes above 3/10, or is worse the next morning, a common approach is to drop back to the previous step.','8–12 weeks','Not medical advice. This section shares general considerations and example exercises commonly used for training injuries. It is not a diagnosis or a treatment plan. Always follow the advice of your doctor, physiotherapist or other medical professional, who can assess you individually. If you''re unsure about anything, check with them first.',array['Pain-free grip strength within 10% side to side (LSI ≥90%) if it can be measured','Wrist curl and pronation at heavy loads pain-free','Heavy pulling, rope work and carries at full training loads pain-free for 2 weeks']::text[],'Consider getting assessed by a physio or doctor if there is no clear improvement after 8–12 weeks, or if tingling into the fingers appears. If you''re unsure, check with your medical professional.',false,'{}'::text[],array['Any change in approach needed if ulnar nerve symptoms are present?']::text[],'Overuse','Draft'),
('wrist','Wrist pain (including ulnar-sided / TFCC)','Loaded wrist extension pain; triangular fibrocartilage complex (TFCC) irritation','Wrist','Pain at the back of the wrist when it''s loaded in extension (burpees, push-ups, front rack, catching a ball), or on the little-finger side of the wrist with gripping, twisting and heavy pulling (often linked to the TFCC). The usual approach is to reduce painful loaded positions, rebuild forearm and grip strength, then gradually restore weight-bearing. After a fall, a scan may be needed first.',array['Pain after a fall onto an outstretched hand, especially in the hollow at the base of the thumb (possible scaphoid fracture: get it checked even if it seems minor; an early X-ray can look normal, so follow-up imaging is common)','Swelling, deformity or can''t grip','Clicking with pain, or the wrist feeling unstable','Numbness or tingling in the fingers','Constant pain at night or at rest, especially with fever, feeling unwell or unexplained weight loss','A hot, red, swollen joint with fever: seek same-day care']::text[],'A commonly used pain-monitoring guide (confirm with your medical professional): pain up to 3/10 during exercise is usually acceptable if it settles within 24 hours and morning symptoms are no worse the next day. If pain goes above 3/10, or is worse the next morning, a common approach is to drop back to the previous step.','6–12 weeks','Not medical advice. This section shares general considerations and example exercises commonly used for training injuries. It is not a diagnosis or a treatment plan. Always follow the advice of your doctor, physiotherapist or other medical professional, who can assess you individually. If you''re unsure about anything, check with them first.',array['Full, pain-free wrist range','Grip strength within 10% side to side (LSI ≥90%) if it can be measured','Push-ups, burpees, front rack and catching at full training volume pain-free','Heavy pulling and carries at full training loads pain-free for 2 weeks']::text[],'Consider getting assessed by a physio or doctor if there was a fall, if clicking and weakness continue, or if there''s no clear improvement after 6 weeks. If you''re unsure, check with your medical professional.',false,'{}'::text[],array['Is one framework for dorsal and ulnar-sided (TFCC) wrist pain acceptable, with the notes marking TFCC-specific work?','Should wrist taping or a wrist wrap be listed as an optional comfort aid?']::text[],'Overuse','Draft'),
('pec','Pectoral strain','Pec major muscle strain','Chest','A pulling or sharp pain in the chest or front of the armpit, usually during heavy pressing, a fast push (burpees, sled push) or a fall. Mild strains of the muscle usually respond to a staged return. A tear of the tendon near the upper arm is different and needs prompt medical assessment, so this framework starts only once that has been ruled out.',array['A pop, then bruising spreading into the upper arm, or a change in the shape of the front of the armpit (possible tendon rupture: get assessed promptly, as timing can matter)','Marked weakness pushing or bringing the arm across the body','Chest pain with breathlessness, sweating or feeling unwell: call 000','Constant pain at night or at rest, especially with fever, feeling unwell or unexplained weight loss','A hot, red, swollen joint with fever: seek same-day care']::text[],'A commonly used pain-monitoring guide (confirm with your medical professional): in the first phase, keep exercises pain-free or close to it (0–2/10). From Phase 2, pain up to 3/10 is usually acceptable if it settles within 24 hours. Sharp pain, a feeling of weakness or giving way, or new bruising is usually a sign to stop and check with them.','3–8 weeks for mild muscle strains','Not medical advice. This section shares general considerations and example exercises commonly used for training injuries. It is not a diagnosis or a treatment plan. Always follow the advice of your doctor, physiotherapist or other medical professional, who can assess you individually. If you''re unsure about anything, check with them first.',array['Full, pain-free range including the arm out to the side and overhead','Pressing strength within 10% of the pre-injury level','Plyometric push-ups pain-free','Pushing, burpees and throwing at full training volume pain-free']::text[],'Acute injuries are usually best assessed promptly by a doctor or physio. This framework is intended only once a tendon tear has been ruled out, under their guidance. If you''re unsure, check with your medical professional.',true,array['This framework assumes a clinician has ruled out a pec major tendon rupture (bruising into the arm, change in the armpit fold, weakness).','The clinician sets the start of each phase based on the grade of strain.']::text[],array['Confirm timelines for mild muscle-belly strains.','When should heavy bench pressing be reintroduced?']::text[],'Acute','Draft'),
('triceps','Triceps tendinopathy or strain','Distal triceps tendinopathy / triceps muscle strain','Back of elbow / upper arm','Pain at the back of the elbow or upper arm with pushing and straightening the arm against load: pressing, push-ups, burpees and throwing. Most cases are overuse and settle with load changes and progressive triceps strengthening. A sudden pop with weakness is different and needs prompt assessment.',array['A pop at the back of the elbow with bruising or a gap, or can''t straighten the arm against resistance (possible tendon rupture: get assessed promptly)','Swelling over the point of the elbow, especially if red, hot or with fever (possible infected bursitis: seek same-day care)','Pins and needles into the hand','Constant pain at night or at rest, especially with fever, feeling unwell or unexplained weight loss']::text[],'A commonly used pain-monitoring guide (confirm with your medical professional): pain up to 3/10 during exercise is usually acceptable if it settles within 24 hours and morning symptoms are no worse the next day. If pain goes above 3/10, or is worse the next morning, a common approach is to drop back to the previous step.','6–10 weeks','Not medical advice. This section shares general considerations and example exercises commonly used for training injuries. It is not a diagnosis or a treatment plan. Always follow the advice of your doctor, physiotherapist or other medical professional, who can assess you individually. If you''re unsure about anything, check with them first.',array['Elbow extension strength within 10% side to side if it can be measured','Close-grip pressing and overhead triceps extension at pre-injury loads pain-free','Pressing, pushing, burpees and throwing at full training volume pain-free for 2 weeks']::text[],'Consider getting assessed by a physio or doctor if there is no clear improvement after 6–8 weeks. Sudden onset with weakness is usually best assessed promptly. If you''re unsure, check with your medical professional.',false,'{}'::text[],array['Is one framework for distal tendinopathy and muscle strain acceptable?','Overhead triceps extension loads the tendon in a lengthened position: Phase 3 only?']::text[],'Overuse','Draft');

insert into public.rehab_phases (program_id,phase_no,name,typical_duration,goal,entry_criteria,exit_criteria,frequency,running_guidance,healing_stage,training_focus) values
('rcrsp',1,'Settle and activate','1–3 weeks','Settle the irritable movements while keeping the shoulder moving and the rotator cuff working.','Shoulder pain with lifting or reaching; no red flags.','Arm lifts overhead with pain ≤2/10; band external rotation 3 × 15 at pain ≤2/10.','Isometrics daily if they help; other exercises every second day','Running, lower-body training and the bike usually continue. Overhead work and high-volume pulling or rowing are commonly paused or reduced if they aggravate it.','Proliferative','Move'),
('rcrsp',2,'Build capacity','3–6 weeks','Build rotator cuff and shoulder blade strength, working towards shoulder height and overhead.','Phase 1 exit criteria met.','Side-lying external rotation 3 × 12 with a moderate dumbbell pain-free; landmine press 3 × 10 each side at pain ≤2/10.','Strength 3 × per week','Keep training what doesn''t hurt. Pushing and pulling can usually build back gradually below shoulder height; overhead work waits until Phase 3.','Proliferative','Volume and load capacity'),
('rcrsp',3,'Overhead and power','3–6 weeks','Restore overhead strength and speed, then return to full training.','Phase 2 exit criteria met.','Discharge criteria met.','Strength 2–3 × per week; power 2 × per week','Bring back overhead and fast work one exercise at a time, adding the next only once the last is pain-free the following morning.','Remodelling','Speed and power'),
('biceps_lhb',1,'Settle','1–3 weeks','Reduce irritation while keeping the arm and shoulder working.','Front-of-shoulder pain with pulling or lifting; no red flags.','Isometric elbow flexion 5 × 45 s pain-free; band row 3 × 15 at pain ≤2/10.','Isometrics daily; other exercises every second day','Running and lower-body training usually continue. Heavy pulling, rope work and heavy carries are commonly paused.','Proliferative','Move'),
('biceps_lhb',2,'Build capacity','3–6 weeks','Progressively load elbow flexion and the shoulder.','Phase 1 exit criteria met.','Eccentric biceps curl 3 × 8 and hammer curl 3 × 10 at a moderate load pain-free; farmers hold 3 × 30 s pain-free.','Strength 3 × per week','Keep training what doesn''t hurt. Pulling and carries can usually build back gradually at lighter loads.','Proliferative','Volume and load capacity'),
('biceps_lhb',3,'Return to pulling and full training','3–6 weeks','Restore heavy pulling and carrying, then return to full training.','Phase 2 exit criteria met.','Discharge criteria met.','Strength 2–3 × per week','Bring back heavy pulling and carries one at a time, building distance before load.','Remodelling','Speed and power'),
('acj',1,'Protect and move','1–2 weeks','Inflammatory phase: commonly protect the joint with relative rest, letting pain guide gentle movement.','Assessed as a mild sprain by a medical professional.','Arm lifts to shoulder height with pain ≤2/10; daily tasks comfortable.','Gentle movement 2–3 × daily','Running (if arm swing is comfortable), the bike and lower-body training without load on the shoulder commonly continue. Pressing, carries and loads on the shoulder are commonly paused, and falls avoided.','Inflammatory','Move'),
('acj',2,'Restore strength','1–4 weeks','Restore full range and rebuild shoulder and shoulder blade strength.','Phase 1 exit criteria met.','Full range overhead pain-free; incline push-up 3 × 10 pain-free.','Strength 3 × per week','Keep training what doesn''t hurt. Carries, dips, bench press and pressing across the body are commonly left until Phase 3 (hanging weight pulls on the joint).','Proliferative','Volume and load capacity'),
('acj',3,'Return to pressing and full training','2–4 weeks','Rebuild pressing and weight-bearing, then return to full training.','Phase 2 exit criteria met.','Discharge criteria met.','Strength 2–3 × per week','Bring back carries, burpees and pressing one at a time. Loads resting on the shoulder, bench press and dips are usually last.','Remodelling','Speed and power'),
('elbow_lat',1,'Settle','1–3 weeks','Reduce irritation: change grips and loads that provoke it and keep the tendon working.','Outer elbow pain with gripping; no red flags.','Isometric wrist extension 5 × 45 s pain-free; grip pain ≤2/10.','Isometrics daily; other exercises every second day','Running and lower-body training usually continue. Common changes: neutral or palms-up grips, straps for pulling, lighter carries, and pausing heavy pulling and rope work.','Proliferative','Move'),
('elbow_lat',2,'Build capacity','4–6 weeks','Slow, progressive loading of the wrist extensors and grip.','Phase 1 exit criteria met.','Reverse wrist curl 3 × 15 with a moderate load at pain ≤2/10; farmers hold 3 × 30 s at pain ≤2/10.','Strength 3 × per week','Keep training what doesn''t hurt. Carries can restart light; heavy pulling stays light or uses straps.','Proliferative','Volume and load capacity'),
('elbow_lat',3,'Return to grip and full training','4–6 weeks','Rebuild heavy and sustained grip, then return to full training.','Phase 2 exit criteria met.','Discharge criteria met.','Strength 2–3 × per week','Bring back rope work and heavy pulling at lighter loads first. Build carry distance before carry weight.','Remodelling','Speed and power'),
('elbow_med',1,'Settle','1–3 weeks','Reduce irritation while keeping the forearm working.','Inner elbow pain with gripping or pulling; no nerve symptoms.','Isometric wrist flexion 5 × 45 s pain-free; grip pain ≤2/10.','Isometrics daily; other exercises every second day','Running and lower-body training usually continue. Common changes: straps, lighter carries, and pausing heavy pulling and rope work.','Proliferative','Move'),
('elbow_med',2,'Build capacity','4–6 weeks','Progressive loading of the wrist flexors, forearm rotators and grip.','Phase 1 exit criteria met.','Wrist curl 3 × 15 with a moderate load at pain ≤2/10; farmers hold 3 × 30 s at pain ≤2/10.','Strength 3 × per week','Keep training what doesn''t hurt. Carries can restart light.','Proliferative','Volume and load capacity'),
('elbow_med',3,'Return to grip and full training','4–6 weeks','Rebuild heavy grip and pulling, then return to full training.','Phase 2 exit criteria met.','Discharge criteria met.','Strength 2–3 × per week','Bring back rope work, then heavy pulling at lighter loads, then full loads.','Remodelling','Speed and power'),
('wrist',1,'Settle and unload','1–3 weeks','Avoid painful loaded wrist positions and keep the forearm working.','Wrist pain with loading; no fall or red flags (or cleared after assessment).','Isometric holds pain-free; push-up on handles 3 × 8 at pain ≤2/10.','Isometrics daily; other exercises every second day','Running and most lower-body training continue. Common changes: push-ups on handles or fists (neutral wrist), burpees with hands on dumbbells or a box, a goblet hold instead of front rack, and pausing catching and throwing.','Proliferative','Move'),
('wrist',2,'Build capacity and weight-bearing','3–5 weeks','Strengthen the forearm and gradually reintroduce weight through the hands.','Phase 1 exit criteria met.','Quadruped hold 3 × 30 s and incline push-up 3 × 10 on flat hands at pain ≤2/10; wrist curls and reverse wrist curls 3 × 12 pain-free.','Strength 3 × per week','Keep training what doesn''t hurt. Carries can restart light; burpees stay modified.','Proliferative','Volume and load capacity'),
('wrist',3,'Return to loaded positions','2–4 weeks','Restore full weight-bearing, front rack and catching, then return to full training.','Phase 2 exit criteria met.','Discharge criteria met.','Strength 2–3 × per week','Bring back burpees on flat hands, then front rack and catching, then heavy pulling.','Remodelling','Speed and power'),
('pec',1,'Protect and move','1–2 weeks','Inflammatory phase: commonly protect the muscle with relative rest, letting pain guide gentle movement.','Assessed as a mild muscle strain; tendon rupture ruled out.','Arm moves through most of its range with pain ≤2/10; gentle palm press pain-free.','Gentle movement daily','Running (easy), the bike and lower-body training commonly continue. Pressing, push-ups, burpees and heavy pushing are commonly paused.','Inflammatory','Move'),
('pec',2,'Rebuild pressing','2–4 weeks','Restore range and progressively load the chest in a comfortable range.','Phase 1 exit criteria met.','Push-up 3 × 10 pain-free; dumbbell floor press 3 × 10 at a moderate load pain-free.','Strength 3 × per week','Keep training what doesn''t hurt. Pushing can usually restart light once incline push-ups are pain-free.','Proliferative','Volume and load capacity'),
('pec',3,'Heavy and fast pressing','2–4 weeks','Restore full-range heavy pressing and fast pushing, then return to full training.','Phase 2 exit criteria met.','Discharge criteria met.','Strength 2–3 × per week; power 2 × per week','Bring back heavy pushing, then burpees, then fast pressing and throwing.','Remodelling','Speed and power'),
('triceps',1,'Settle','1–2 weeks','Reduce irritation while keeping the triceps working.','Pain at the back of the elbow with pushing; no rupture signs.','Isometric elbow extension 5 × 45 s pain-free; incline push-up 3 × 10 at pain ≤2/10.','Isometrics daily; other exercises every second day','Running and lower-body training usually continue. Pressing, heavy pushing and burpees are commonly paused or modified (step-down burpees).','Proliferative','Move'),
('triceps',2,'Build capacity','2–4 weeks','Progressive triceps loading through a comfortable range.','Phase 1 exit criteria met.','Rope triceps pushdown 3 × 12 at a moderate load pain-free; push-up 3 × 10 pain-free.','Strength 3 × per week','Keep training what doesn''t hurt. Heavy pushing can restart light.','Proliferative','Volume and load capacity'),
('triceps',3,'Return to pushing and full training','2–4 weeks','Restore heavy and lengthened triceps loading and fast pushing, then return to full training.','Phase 2 exit criteria met.','Discharge criteria met.','Strength 2–3 × per week','Bring back heavy pushing, then burpees, then throwing.','Remodelling','Speed and power');

insert into public.rehab_phase_exercises (program_id,phase_no,sort_order,exercise_id,dose,notes,tempo) values
('rcrsp',1,1,'EX0529','5 × 30–45 s, 30–50% effort','Elbow at your side, press into a wall or doorframe. Optional for pain relief','Hold'),
('rcrsp',1,2,'EX0530','5 × 30–45 s, 30–50% effort','Press the back of the wrist out into a wall','Hold'),
('rcrsp',1,3,'EX0531','3 × 15','Elbow at your side; towel under the arm','3-1-3-1'),
('rcrsp',1,4,'EX0129','3 × 15','Shoulder blades back and down','3-1-3-1'),
('rcrsp',1,5,'EX0267','3 × 10','Only through a comfortable range',null),
('rcrsp',1,6,'EX0087','2 × 10',null,null),
('rcrsp',1,7,'EX0415','3 × 30 s','Shoulder control step 1: push the floor away','Hold'),
('rcrsp',2,1,'EX0533','3 × 12 each side','Slow, full range','3-1-3-1'),
('rcrsp',2,2,'EX0535','3 × 12','Thumbs up, to shoulder height','3-1-3-1'),
('rcrsp',2,3,'EX0536','3 × 10','Light or no weight','3-1-3-1'),
('rcrsp',2,4,'EX0113','3 × 10',null,'3-1-3-1'),
('rcrsp',2,5,'EX0094','3 × 12',null,'3-1-3-1'),
('rcrsp',2,6,'EX0279','3 × 10 each side','A shoulder-friendly step towards overhead','3-1-3-1'),
('rcrsp',2,7,'EX0379','3 × 12',null,'3-1-3-1'),
('rcrsp',2,8,'EX0205','3 × 20','Shoulder control step 2',null),
('rcrsp',3,1,'EX0534','3 × 12','Arm at shoulder height','3-1-C-1'),
('rcrsp',3,2,'EX0377','3 × 8 each side',null,'3-1-C-1'),
('rcrsp',3,3,'EX0085','3 × 10',null,'3-1-C-1'),
('rcrsp',3,4,'EX0257','3 × 20 s each side','Shoulder control step 4','Hold'),
('rcrsp',3,5,'EX0537','3 × 20 s each side','Fast, small circles',null),
('rcrsp',3,6,'EX0343','3 × 8',null,null),
('rcrsp',3,7,'EX0349','3 × 6',null,null),
('rcrsp',3,8,'EX0199','3 × 10, light ball','Build load and reps gradually',null),
('biceps_lhb',1,1,'EX0540','5 × 30–45 s, 30–50% effort','Elbow at 90°, palm up','Hold'),
('biceps_lhb',1,2,'EX0529','5 × 30 s',null,'Hold'),
('biceps_lhb',1,3,'EX0129','3 × 15',null,'3-1-3-1'),
('biceps_lhb',1,4,'EX0531','3 × 15',null,'3-1-3-1'),
('biceps_lhb',1,5,'EX0267','3 × 10',null,null),
('biceps_lhb',1,6,'EX0087','2 × 10',null,null),
('biceps_lhb',2,1,'EX0542','3 × 8','Lift with two hands, lower slowly with one','4-0-C-0'),
('biceps_lhb',2,2,'EX0235','3 × 10',null,'3-1-3-1'),
('biceps_lhb',2,3,'EX0533','3 × 12 each side',null,'3-1-3-1'),
('biceps_lhb',2,4,'EX0113','3 × 10',null,'3-1-3-1'),
('biceps_lhb',2,5,'EX0094','3 × 12',null,'3-1-3-1'),
('biceps_lhb',2,6,'EX0219','3 × 30 s','Build grip and carry tolerance','Hold'),
('biceps_lhb',3,1,'EX0227','3 × 8, heavier',null,'3-1-C-1'),
('biceps_lhb',3,2,'EX0464','3 × 10','Lengthened position: check with your physio','3-1-C-1'),
('biceps_lhb',3,3,'EX0223','3 × 10',null,'3-1-C-1'),
('biceps_lhb',3,4,'EX0228','3 × 20 m','Build to fast once comfortable',null),
('biceps_lhb',3,5,'EX0238','4 × 12.5 m, light','Build load gradually',null),
('biceps_lhb',3,6,'EX0243','3 × 40 m',null,null),
('acj',1,1,'EX0538','2 × 30 s, several times a day','Relaxed arm',null),
('acj',1,2,'EX0539','2 × 10','Other arm does the work',null),
('acj',1,3,'EX0529','3 × 20 s, gentle',null,'Hold'),
('acj',1,4,'EX0530','3 × 20 s, gentle',null,'Hold'),
('acj',1,5,'EX0129','2 × 15, light','If comfortable','3-1-3-1'),
('acj',2,1,'EX0267','3 × 10',null,null),
('acj',2,2,'EX0531','3 × 15',null,'3-1-3-1'),
('acj',2,3,'EX0113','3 × 10',null,'3-1-3-1'),
('acj',2,4,'EX0535','3 × 12',null,'3-1-3-1'),
('acj',2,5,'EX0179','3 × 10','Hands high first, then lower','3-1-3-1'),
('acj',2,6,'EX0415','3 × 30 s','Shoulder control step 1','Hold'),
('acj',3,1,'EX0175','3 × 10',null,'3-1-C-1'),
('acj',3,2,'EX0279','3 × 10 each side',null,'3-1-C-1'),
('acj',3,3,'EX0449','3 × 10','Limits the bottom range','3-1-C-1'),
('acj',3,4,'EX0205','3 × 20','Shoulder control step 2',null),
('acj',3,5,'EX0206','3 × 10 m','Shoulder control step 3',null),
('acj',3,6,'EX0195','4 × 12.5 m, moderate',null,null),
('acj',3,7,'EX0243','3 × 30 m, light','Build distance, then weight',null),
('acj',3,8,'EX0197','3 × 8','Step down first if needed',null),
('elbow_lat',1,1,'EX0543','5 × 30–45 s','Elbow bent at first, then straighter','Hold'),
('elbow_lat',1,2,'EX0249','3 × 15, light',null,null),
('elbow_lat',1,3,'EX0129','3 × 15','Neutral grip','3-1-3-1'),
('elbow_lat',1,4,'EX0531','3 × 15','Shoulder strength supports the elbow','3-1-3-1'),
('elbow_lat',1,5,'EX0359','2 × 10',null,null),
('elbow_lat',2,1,'EX0545','3 × 15','Lift with the other hand, lower slowly','4-0-C-0'),
('elbow_lat',2,2,'EX0232','3 × 12',null,'3-1-3-1'),
('elbow_lat',2,3,'EX0547','3 × 12',null,'3-1-3-1'),
('elbow_lat',2,4,'EX0235','3 × 10',null,'3-1-3-1'),
('elbow_lat',2,5,'EX0113','3 × 10','Neutral grip','3-1-3-1'),
('elbow_lat',2,6,'EX0219','3 × 30 s',null,'Hold'),
('elbow_lat',3,1,'EX0232','3 × 10, heavier',null,'3-1-C-1'),
('elbow_lat',3,2,'EX0245','3 × 2 up and down',null,null),
('elbow_lat',3,3,'EX0256','3 × 20 s',null,'Hold'),
('elbow_lat',3,4,'EX0226','3 × 20–30 s',null,'Hold'),
('elbow_lat',3,5,'EX0218','3 × 15 m','Build to fast once comfortable',null),
('elbow_lat',3,6,'EX0243','3 × 40 m',null,null),
('elbow_lat',3,7,'EX0238','4 × 12.5 m, light','Build load gradually',null),
('elbow_med',1,1,'EX0544','5 × 30–45 s',null,'Hold'),
('elbow_med',1,2,'EX0548','5 × 30 s','Palm-down direction','Hold'),
('elbow_med',1,3,'EX0249','3 × 15, light',null,null),
('elbow_med',1,4,'EX0129','3 × 15',null,'3-1-3-1'),
('elbow_med',1,5,'EX0359','2 × 10',null,null),
('elbow_med',2,1,'EX0546','3 × 15','Lift with the other hand, lower slowly','4-0-C-0'),
('elbow_med',2,2,'EX0246','3 × 12',null,'3-1-3-1'),
('elbow_med',2,3,'EX0547','3 × 12',null,'3-1-3-1'),
('elbow_med',2,4,'EX0235','3 × 10',null,'3-1-3-1'),
('elbow_med',2,5,'EX0113','3 × 10',null,'3-1-3-1'),
('elbow_med',2,6,'EX0219','3 × 30 s',null,'Hold'),
('elbow_med',3,1,'EX0246','3 × 10, heavier',null,'3-1-C-1'),
('elbow_med',3,2,'EX0245','3 × 2 up and down',null,null),
('elbow_med',3,3,'EX0234','3 × 15–20 s',null,'Hold'),
('elbow_med',3,4,'EX0218','3 × 15 m','Build to fast once comfortable',null),
('elbow_med',3,5,'EX0243','3 × 40 m',null,null),
('elbow_med',3,6,'EX0238','4 × 12.5 m, light','Build load gradually',null),
('wrist',1,1,'EX0543','4 × 30 s',null,'Hold'),
('wrist',1,2,'EX0544','4 × 30 s',null,'Hold'),
('wrist',1,3,'EX0548','4 × 30 s each way','Ulnar-sided (TFCC) pain: a common focus','Hold'),
('wrist',1,4,'EX0359','2 × 10','Comfortable range',null),
('wrist',1,5,'EX0249','3 × 15, light',null,null),
('wrist',1,6,'EX0550','3 × 8','Keeps the wrist neutral','3-1-3-1'),
('wrist',2,1,'EX0246','3 × 12',null,'3-1-3-1'),
('wrist',2,2,'EX0232','3 × 12',null,'3-1-3-1'),
('wrist',2,3,'EX0547','3 × 12','Ulnar-sided (TFCC) pain: build slowly','3-1-3-1'),
('wrist',2,4,'EX0549','3 × 10','Build range gradually',null),
('wrist',2,5,'EX0415','3 × 30 s','Flat hands','Hold'),
('wrist',2,6,'EX0179','3 × 10','Flat hands, hands high','3-1-3-1'),
('wrist',2,7,'EX0219','3 × 30 s',null,'Hold'),
('wrist',3,1,'EX0175','3 × 10',null,'3-1-C-1'),
('wrist',3,2,'EX0205','3 × 20',null,null),
('wrist',3,3,'EX0206','3 × 10 m',null,null),
('wrist',3,4,'EX0345','3 × 20 s','Light','Hold'),
('wrist',3,5,'EX0245','3 × 2 up and down',null,null),
('wrist',3,6,'EX0343','3 × 8','Catching loads the wrist quickly',null),
('wrist',3,7,'EX0197','3 × 8',null,null),
('wrist',3,8,'EX0199','3 × 10, light ball','Build load gradually',null),
('pec',1,1,'EX0539','2 × 10','Gentle',null),
('pec',1,2,'EX0551','5 × 20 s, light','Hands pressed together in front of the chest','Hold'),
('pec',1,3,'EX0129','3 × 15',null,'3-1-3-1'),
('pec',1,4,'EX0531','3 × 15',null,'3-1-3-1'),
('pec',1,5,'EX0087','2 × 10',null,null),
('pec',2,1,'EX0179','3 × 12',null,'3-1-3-1'),
('pec',2,2,'EX0449','3 × 10','Floor limits the stretched range','3-1-3-1'),
('pec',2,3,'EX0455','3 × 12, light','Small range first','3-1-3-1'),
('pec',2,4,'EX0090','2 × 30 s','Gentle; only as comfortable',null),
('pec',2,5,'EX0113','3 × 10',null,'3-1-3-1'),
('pec',2,6,'EX0175','3 × 8–10',null,'3-1-3-1'),
('pec',3,1,'EX0446','3 × 8',null,'3-1-C-1'),
('pec',3,2,'EX0400','3 × 8',null,'3-1-3-0'),
('pec',3,3,'EX0343','3 × 8',null,null),
('pec',3,4,'EX0398','3 × 5','Last step',null),
('pec',3,5,'EX0195','4 × 12.5 m',null,null),
('pec',3,6,'EX0197','3 × 10',null,null),
('triceps',1,1,'EX0541','5 × 30–45 s, 30–50% effort','Elbow bent to 90°','Hold'),
('triceps',1,2,'EX0552','3 × 15, light',null,'3-1-3-1'),
('triceps',1,3,'EX0129','3 × 15',null,'3-1-3-1'),
('triceps',1,4,'EX0531','3 × 15',null,'3-1-3-1'),
('triceps',1,5,'EX0179','3 × 10','Hands high','3-1-3-1'),
('triceps',2,1,'EX0078','3 × 12',null,'3-1-3-1'),
('triceps',2,2,'EX0449','3 × 10',null,'3-1-3-1'),
('triceps',2,3,'EX0175','3 × 10',null,'3-1-3-1'),
('triceps',2,4,'EX0279','3 × 10 each side',null,'3-1-3-1'),
('triceps',2,5,'EX0113','3 × 10',null,'3-1-3-1'),
('triceps',3,1,'EX0457','3 × 10','Lengthened position','3-1-C-1'),
('triceps',3,2,'EX0450','3 × 8',null,'3-1-C-1'),
('triceps',3,3,'EX0400','3 × 8',null,'3-1-3-0'),
('triceps',3,4,'EX0343','3 × 8',null,null),
('triceps',3,5,'EX0195','4 × 12.5 m',null,null),
('triceps',3,6,'EX0199','3 × 10, light ball','Build load gradually',null);

-- Check after push (expected): exercises 552 | rehab_programs 18 | guidance 16 | new rehab rows 149
