-- =====================================================================
-- HYATHLON INSTALL · PART 3d · rehab wording: considerations, not medical advice
-- Run AFTER Parts 3, 3b and 3c. Contains no personal data. SQL Editor → New query → Run. One transaction.
-- =====================================================================
begin;
set local search_path = public, extensions;

-- 1) Rehab content v4: considerations, not medical advice ----------------
alter table public.rehab_programs alter column disclaimer set default 'Not medical advice. This section shares general considerations and example exercises commonly used for running injuries. It is not a diagnosis or a treatment plan. Always follow the advice of your doctor, physiotherapist or other medical professional, who can assess you individually. If you''re unsure about anything, check with them first.';


insert into public.rehab_global_guidance (key,title,items,sort_order) values
('disclaimer','About these programs',array['Not medical advice. This section shares general considerations and example exercises commonly used for running injuries. It is not a diagnosis or a treatment plan. Always follow the advice of your doctor, physiotherapist or other medical professional, who can assess you individually. If you''re unsure about anything, check with them first.']::text[],1),
('stop_and_seek_advice','Be aware: speak to a physio or doctor if you notice',array['Pain that doesn''t go away with rest, or gets worse with training','Pain that changes how you run, lift or move','Swelling or bruising around a joint or muscle','Sudden sharp or stabbing pain during training','Reduced range of motion or weakness','No improvement after several days of rest, or after 4–6 weeks of this program','Unable to bear weight or walk normally','Numbness, tingling or pins and needles','Pain that wakes you or stops you sleeping']::text[],2),
('emergency','Stop immediately and get urgent medical help',array['Chest pain or pressure','Difficulty breathing','Sudden headache, confusion, slurred speech, weakness or numbness on one side','Collapse, fainting or loss of consciousness','Signs of heat illness: confusion, stopping sweating, hot skin, vomiting','Severe injury: obvious deformity, a joint that won''t move, heavy bleeding','Calf swelling, warmth and tenderness with no injury (possible blood clot)','If someone collapses and is unresponsive: call 000 (Australia), start CPR and use an AED if available.']::text[],3),
('medications','Medications',array['Some medicines can affect healing or tendons. Discuss any medications, including anti-inflammatories and antibiotics, with your doctor or pharmacist.']::text[],4),
('coach_role','The coach''s role',array['Coaches don''t diagnose or treat injuries, but are often the first line of help.','For new soreness or mild pain, a coach can reduce or pause the aggravating training and swap running for non-impact cardio (bike, ergs, swimming), then follow up closely.','Keep a detailed training log. Athletes can share it with their doctor or physio as objective data for rehab decisions.','Refer on whenever any stop-and-seek-advice sign appears.']::text[],5),
('acute_vs_overuse','Acute vs overuse injuries',array['Acute: sudden onset from a specific incident (ankle roll, muscle strain during a lift or sprint, a pop or snap). Prompt medical assessment is usually recommended.','Overuse: develops gradually from repeated load without enough recovery (runner''s knee, Achilles or plantar pain, shin splints). Usually managed by adjusting training, with assessment if not improving.','Most issues coaches see are overuse, mainly from running, but acute injuries can mean surgery or long time away, so recognise them early.']::text[],6),
('healing_phases','How tissue heals (general considerations)',array['General considerations only; your medical professional will guide what suits your injury.','Inflammatory phase (first days after an acute injury): commonly protect with relative rest and elevation. Pain guides what''s tolerable. Let the body do its work.','Proliferative phase (quantitative): restore mobility, stability, proprioception and load capacity. Load according to pain.','Remodelling phase (qualitative): increase range, apply specific loading, and build towards strength and power for full recovery.','Overuse injuries often skip the inflammatory phase and start at the proliferative stage.']::text[],7),
('progression_principle','Move, then volume, then speed',array['Rehab follows the strength and force–velocity continuum: restore movement first, build load capacity and volume next, then add speed and power last.','Each overload is followed by recovery; progress only once the body has adapted (supercompensation). Too much too soon leads to decompensation.']::text[],8),
('proprioception_progression','Proprioception progression',array['Step 1: static single-leg stance, eyes open','Step 2: static single-leg stance, eyes closed','Step 3: dynamic steps or hops, eyes open','Step 4: dynamic steps or hops, eyes closed after landing','Step 5: dynamic steps or hops, eyes closed','Always start with the better side. Only progress once both sides are good. This is quality training: stop the set when control drops.']::text[],9),
('tempo_notation','Tempo notation',array['Four numbers: lowering (eccentric) – pause at the bottom – lifting (concentric) – pause at the top, in seconds.','C means the lift is performed with control at a natural speed.','Example: squat 4-1-C-1 = 4 s down, 1 s pause, controlled up, 1 s pause at the top.','Hold = isometric (no movement) for the time given.']::text[],10),
('unilateral_gait','Single-leg strength for gait',array['Running and most race stations are single-leg, alternating movements. Rehab and prevention put single-leg work first.','Key muscles for gait: glute max (drives weight transfer), hamstrings (hip extension), adductor magnus (shifts weight over the stance leg) and the obliques (connect ribs and pelvis).','Build control first, then strength, then endurance, so the gait muscles last for the whole race.']::text[],11),
('heat','Training and racing in heat',array['Exertional heat illness ranges from cramps and heat exhaustion to heat stroke. Anyone who collapses or becomes confused needs urgent medical assessment.','Sweat losses vary widely (about 0.5–2.5 L and 500–6000 mg sodium per hour). Work out individual sweat and sodium needs in training.','Build heat exposure gradually, like any other training stimulus, and avoid long or hard sessions in dangerous conditions.','Wet-bulb temperature 28–30 °C (82–86 °F): 1:1 work-to-rest. Above 30 °C (86 °F): postpone training or competition.','Watch for exercise-associated cramps, low sodium (hyponatremia), exertional collapse and rhabdomyolysis (dark urine, severe muscle pain).','Follow the guidance of event medical staff and your own doctor.']::text[],12),
('erg_overuse','Overuse from ergs and stations',array['SkiErg: shoulder (rotator cuff, impingement), elbow and lower back.','Rower: lower back, quad or hamstring tendons, elbow.','Low-impact still means load: build erg volume gradually, like running.','In HYROX race data, most medical visits were for calf and shin complaints during running, and cramping linked to preparation, fuelling and hydration.']::text[],13),
('exercise_risk','Choosing exercises to limit acute injury risk',array['Heavy loads, high speed and explosive movements raise the risk of acute injury. Match exercises to the athlete''s skill and experience.','Avoid Olympic lifts for athletes without experience; use safer alternatives with a similar stimulus.','High-rep, maximum-distance burpee broad jumps and overloaded sleds add tendon and landing stress; build up gradually.','Always warm up and activate, consider the athlete''s age and history, and err on the side of caution.']::text[],14),
('care_team','Working with your medical professional',array['Your doctor or physio can build or adjust your rehab plan in the app, and you can customise your own plan with them.','You can send them a summary of your training history at any time. It''s only ever sent when you choose to.']::text[],15)
on conflict (key) do update set title=excluded.title, items=excluded.items, sort_order=excluded.sort_order;

delete from public.rehab_programs;
delete from public.return_to_run_plans;

insert into public.rehab_programs (id,name,also_known_as,body_area,overview,red_flags,pain_rule,typical_duration,disclaimer,discharge_criteria,seek_assessment,clinician_required,clinician_notes,physio_review_points,injury_type) values
('mtss','Shin splints','Medial tibial stress syndrome (MTSS)','Lower leg','Diffuse pain along the inner border of the shin, usually from a rise in running load. The aim is to settle the bone and muscle, rebuild calf and shin capacity, then rebuild running.',array['Pain in one small spot on the bone (possible bone stress injury: see a professional before continuing)','Pain when resting or at night','Pain that gets worse with each hop on one leg','Tight, burning or numb lower leg during exercise that eases with rest (possible compartment syndrome)']::text[],'A commonly used pain-monitoring guide (confirm with your medical professional): pain up to 3/10 during exercise is acceptable if it settles within 24 hours and morning symptoms are no worse the next day. If pain goes above 3/10, or is worse the next morning, drop back to the previous step.','6–12 weeks','Not medical advice. This section shares general considerations and example exercises commonly used for running injuries. It is not a diagnosis or a treatment plan. Always follow the advice of your doctor, physiotherapist or other medical professional, who can assess you individually. If you''re unsure about anything, check with them first.',array['25+ single-leg calf raises each side, with the injured side within 10% of the other (LSI ≥90%)','Single-leg hop for distance LSI ≥90%','2 × 20 single-leg pogo hops each side, pain-free','2 weeks at pre-injury running volume with no symptoms']::text[],'Consider getting assessed by a medical professional if pain becomes focal on the bone, or there is no improvement after 3–4 weeks.',false,'{}'::text[],array['Is a symptom-guided progression preferred over any fixed weekly increase for this group?','Should a hop test be required before starting Phase 3?','Confirm healing-stage labels and the move → volume → speed focus for each phase.','Confirm tempo prescriptions and the proprioception progression placement.']::text[],'Overuse'),
('pfps','Runner''s knee','Patellofemoral pain (PFP)','Knee','Pain around or behind the kneecap, worse with stairs, squats, downhill running or sitting for long periods. The aim is to calm the knee, then build quad and hip strength.',array['Knee locking, catching or giving way','Swelling, especially after a twist or fall','Pain on the joint line at the side of the knee','Pain at rest or at night']::text[],'A commonly used pain-monitoring guide (confirm with your medical professional): pain up to 3/10 during exercise is acceptable if it settles within 24 hours and morning symptoms are no worse the next day. If pain goes above 3/10, or is worse the next morning, drop back to the previous step.','6–12 weeks','Not medical advice. This section shares general considerations and example exercises commonly used for running injuries. It is not a diagnosis or a treatment plan. Always follow the advice of your doctor, physiotherapist or other medical professional, who can assess you individually. If you''re unsure about anything, check with them first.',array['10 single-leg squats to a box each side with good knee control (knee stays over the foot)','Single-leg hop for distance and triple hop LSI ≥90%','Quad and hip abduction strength within 10% side to side (if a dynamometer is available)','Stairs, squats, downhill running and full training pain-free']::text[],'Consider getting assessed by a medical professional if there is no clear improvement after 6 weeks.',false,'{}'::text[],array['Knee angle limits for Phase 2 loading (e.g. leg press 0–60°)?','Which functional tests to use at discharge?','Confirm healing-stage labels and the move → volume → speed focus for each phase.','Confirm tempo prescriptions and the proprioception progression placement.']::text[],'Overuse'),
('bsi','Bone stress injury return','Lower-leg bone stress injury (low-risk sites)','Lower leg / foot','For a diagnosed low-risk bone stress injury (for example the back or inner tibia, fibula, or 2nd–4th metatarsal) once a doctor or physio has cleared you to start loading. It is not for high-risk sites.',array['Not yet diagnosed or cleared by a medical professional: do not start','High-risk sites need medical management and are not covered here: front of the tibia, navicular, base of the 5th metatarsal, inner ankle bone, femoral neck','Any bone pain when walking, hopping or at rest','Repeat bone stress injuries, missed or irregular periods, or low energy intake: ask about RED-S screening']::text[],'A commonly used pain-monitoring guide (confirm with your medical professional): bone stress injuries are commonly managed pain-free: 0/10 bone pain during activity and in the 24 hours after. Any bone pain usually means stop and drop back to the previous step.','12–20 weeks from diagnosis','Not medical advice. This section shares general considerations and example exercises commonly used for running injuries. It is not a diagnosis or a treatment plan. Always follow the advice of your doctor, physiotherapist or other medical professional, who can assess you individually. If you''re unsure about anything, check with them first.',array['Full training for 4 weeks with no bone pain','25+ single-leg calf raises each side, LSI ≥90%','Single-leg hop for distance LSI ≥90%, pain-free','Medical sign-off for return to speed work and racing']::text[],'This framework is intended to be used only under the guidance of a doctor or physio. If bone pain returns, contact them promptly.',true,array['Site matters. Low-risk sites (back/inner tibia, fibula, 2nd–4th metatarsal) can usually follow a staged return. High-risk sites (front of the tibia, navicular, base of the 5th metatarsal, inner ankle, femoral neck) need medical management and are excluded.','Timelines depend on site, imaging grade and the individual; the clinician sets the start of each phase.','RED-S considerations: be aware of energy intake, menstrual function (irregular or absent periods), low libido in males, previous bone stress injuries, recent weight loss and fatigue. If any are present, consider discussion with a sports doctor and sports dietitian, who may consider further assessment such as bone density.','Return-to-run criteria (hop test, pain-free walking, bone tenderness) to be confirmed by the treating clinician.']::text[],array['Confirm return-to-run criteria and the bone-stress run plan.','Confirm site-specific exclusions and timelines.','Confirm the RED-S screening questions and referral pathway.','Confirm healing-stage labels and the move → volume → speed focus for each phase.','Confirm tempo prescriptions and the proprioception progression placement.']::text[],'Overuse'),
('achilles_mid','Achilles tendinopathy (mid-portion)','Mid-portion Achilles tendinopathy','Lower leg','Pain and thickening 2–6 cm above the heel, with morning stiffness, often after a rise in speed, hills or volume. Tendons respond to progressive loading, so rest alone rarely fixes it.',array['A sudden pop or feeling of being kicked in the back of the leg (possible rupture: see a doctor urgently)','Unable to do a single-leg calf raise','Marked swelling or a lump that is hot and red','Recent fluoroquinolone antibiotics (for example ciprofloxacin)','Pain in both Achilles plus other joints']::text[],'A commonly used pain-monitoring guide (confirm with your medical professional): pain up to 3/10 during exercise is acceptable if it settles within 24 hours and morning symptoms are no worse the next day. If pain goes above 3/10, or is worse the next morning, drop back to the previous step. For the Achilles, also track morning stiffness: it should not get worse from week to week.','12 weeks or more','Not medical advice. This section shares general considerations and example exercises commonly used for running injuries. It is not a diagnosis or a treatment plan. Always follow the advice of your doctor, physiotherapist or other medical professional, who can assess you individually. If you''re unsure about anything, check with them first.',array['25+ single-leg calf raises each side, LSI ≥90%','Weighted single-leg calf raise 3 × 8 each side','2 × 20 single-leg pogo hops each side at pain ≤2/10','Morning stiffness resolved; VISA-A score improving if your physio uses it']::text[],'Consider getting assessed by a medical professional if there is no clear improvement after 6–8 weeks of loading.',false,'{}'::text[],array['Pain threshold during loading: ≤3/10 as written, or the Silbernagel ≤5/10 model?','Keep eccentric heel drops alongside heavy slow resistance?','Confirm healing-stage labels and the move → volume → speed focus for each phase.','Confirm tempo prescriptions and the proprioception progression placement.']::text[],'Overuse'),
('achilles_ins','Achilles tendinopathy (insertional)','Insertional Achilles tendinopathy','Lower leg','Pain where the Achilles attaches to the back of the heel, often worse with uphill running, stretching the calf and flat or barefoot shoes. Loading is similar to the mid-portion program, but the heel stays on flat ground so the tendon isn''t compressed against the heel bone.',array['A sudden pop or feeling of being kicked in the back of the leg (possible rupture: see a doctor urgently)','Unable to do a single-leg calf raise','Marked swelling or a lump that is hot and red','Recent fluoroquinolone antibiotics (for example ciprofloxacin)','Pain in both Achilles plus other joints']::text[],'A commonly used pain-monitoring guide (confirm with your medical professional): pain up to 3/10 during exercise is acceptable if it settles within 24 hours and morning symptoms are no worse the next day. If pain goes above 3/10, or is worse the next morning, drop back to the previous step. For the Achilles, also track morning stiffness: it should not get worse from week to week.','12 weeks or more','Not medical advice. This section shares general considerations and example exercises commonly used for running injuries. It is not a diagnosis or a treatment plan. Always follow the advice of your doctor, physiotherapist or other medical professional, who can assess you individually. If you''re unsure about anything, check with them first.',array['25+ single-leg calf raises on flat ground each side, LSI ≥90%','Weighted calf raise 3 × 8 each side on flat ground','Pogo hops and uphill running pain-free','Morning stiffness resolved']::text[],'Consider getting assessed by a medical professional if there is no clear improvement after 8 weeks, or if there is a hard lump or redness at the back of the heel.',false,'{}'::text[],array['Use of a heel raise in shoes early on, and when to wean off it?','When to reintroduce range below flat and uphill running?','Confirm healing-stage labels and the move → volume → speed focus for each phase.','Confirm tempo prescriptions and the proprioception progression placement.']::text[],'Overuse'),
('plantar','Plantar fasciitis','Plantar heel pain','Foot','Pain under the heel, typically worst with the first steps in the morning or after sitting. The aim is to settle it and then strengthen the foot and calf with slow, heavy loading.',array['Numbness, tingling or burning in the foot (possible nerve involvement)','Pain when the heel is squeezed from both sides (possible heel bone stress injury)','Swelling, redness or heat','Night pain','Pain in both heels together with other joints']::text[],'A commonly used pain-monitoring guide (confirm with your medical professional): pain up to 3/10 during exercise is acceptable if it settles within 24 hours and morning symptoms are no worse the next day. If pain goes above 3/10, or is worse the next morning, drop back to the previous step.','8–16 weeks','Not medical advice. This section shares general considerations and example exercises commonly used for running injuries. It is not a diagnosis or a treatment plan. Always follow the advice of your doctor, physiotherapist or other medical professional, who can assess you individually. If you''re unsure about anything, check with them first.',array['12 slow single-leg heel raises with toes elevated each side, LSI ≥90%','2 × 20 pogo hops pain-free','No first-step pain in the morning','Full training for 2 weeks without symptoms']::text[],'Consider getting assessed by a medical professional if there is no clear improvement after 6–8 weeks, or if symptoms include numbness or burning.',false,'{}'::text[],array['Is the Rathleff protocol dosing appropriate as written?','Confirm healing-stage labels and the move → volume → speed focus for each phase.','Confirm tempo prescriptions and the proprioception progression placement.']::text[],'Overuse'),
('itbs','IT band syndrome','Iliotibial band syndrome (ITBS)','Hip / knee','Sharp pain on the outside of the knee that comes on at a predictable distance, often worse downhill. The aim is to manage running load and build hip strength and control.',array['Swelling in the knee','Locking or giving way','Pain after a twist or fall','Pain at rest']::text[],'A commonly used pain-monitoring guide (confirm with your medical professional): pain up to 3/10 during exercise is acceptable if it settles within 24 hours and morning symptoms are no worse the next day. If pain goes above 3/10, or is worse the next morning, drop back to the previous step.','6–10 weeks','Not medical advice. This section shares general considerations and example exercises commonly used for running injuries. It is not a diagnosis or a treatment plan. Always follow the advice of your doctor, physiotherapist or other medical professional, who can assess you individually. If you''re unsure about anything, check with them first.',array['Side plank 45 s each side with good alignment','10 single-leg squats each side with good control','Single-leg hop for distance LSI ≥90%','Long runs and downhills pain-free']::text[],'Consider getting assessed by a medical professional if there is no clear improvement after 4–6 weeks.',false,'{}'::text[],array['Keep foam rolling as a comfort-only option or remove it?','Confirm healing-stage labels and the move → volume → speed focus for each phase.','Confirm tempo prescriptions and the proprioception progression placement.']::text[],'Overuse'),
('calf','Calf strain','Gastrocnemius or soleus strain','Lower leg','A sudden sharp pain or pull in the calf, often during speed, hills or sled work. Soleus strains (deep, lower calf) usually take longer than gastrocnemius strains.',array['A pop and being unable to rise onto the toes (rule out Achilles rupture)','Calf swelling, warmth and tenderness without an injury (possible blood clot: seek urgent care)','Large bruising or a visible dent in the muscle','Unable to put weight through the leg']::text[],'A commonly used pain-monitoring guide (confirm with your medical professional): pain up to 3/10 during exercise is acceptable if it settles within 24 hours and morning symptoms are no worse the next day. If pain goes above 3/10, or is worse the next morning, drop back to the previous step.','3–8 weeks','Not medical advice. This section shares general considerations and example exercises commonly used for running injuries. It is not a diagnosis or a treatment plan. Always follow the advice of your doctor, physiotherapist or other medical professional, who can assess you individually. If you''re unsure about anything, check with them first.',array['Straight-knee and bent-knee calf raise endurance LSI ≥90%','Single-leg hop for distance LSI ≥90%','Strides and repeated fast running pain-free','Sled push at race weight pain-free']::text[],'Acute injuries are usually best assessed promptly by a doctor or physio. Consider getting assessed by a medical professional if you can''t walk normally after a week, or if the strain recurs.',false,'{}'::text[],array['Separate timelines for gastrocnemius vs soleus strains?','Confirm healing-stage labels and the move → volume → speed focus for each phase.','Confirm tempo prescriptions and the proprioception progression placement.']::text[],'Acute'),
('pht','Hamstring tendinopathy','Proximal hamstring tendinopathy','Hip / hamstring','Deep pain at the sit bone, worse with sitting, hills, speed and deep hip bending. The aim is to load the tendon progressively while avoiding positions that compress it.',array['A sudden pop with bruising at the back of the thigh (possible avulsion: see a doctor urgently)','Pain spreading down the leg with numbness or tingling (may be coming from the back)','Night pain or fever']::text[],'A commonly used pain-monitoring guide (confirm with your medical professional): pain up to 3/10 during exercise is acceptable if it settles within 24 hours and morning symptoms are no worse the next day. If pain goes above 3/10, or is worse the next morning, drop back to the previous step. Avoid hamstring stretching and long periods of sitting on hard surfaces while symptoms are high.','12 weeks or more','Not medical advice. This section shares general considerations and example exercises commonly used for running injuries. It is not a diagnosis or a treatment plan. Always follow the advice of your doctor, physiotherapist or other medical professional, who can assess you individually. If you''re unsure about anything, check with them first.',array['Single-leg bridge 25+ reps each side, LSI ≥90%','Nordic hamstring curl 3 × 5 pain-free','Sitting 60 min pain-free','Full speed and hill running pain-free']::text[],'Consider getting assessed by a medical professional if there is no clear improvement after 6–8 weeks, or if pain spreads down the leg.',false,'{}'::text[],array['When should hills be reintroduced? (Currently late in Phase 3, after flat strides and speed.)','Confirm healing-stage labels and the move → volume → speed focus for each phase.','Confirm tempo prescriptions and the proprioception progression placement.']::text[],'Overuse'),
('lbp','Hip, SIJ and lower back pain','Non-specific lower back, sacroiliac joint and hip pain','Hip / back','Pain in the lower back, the SIJ (dimples at the back of the pelvis) or around the hip without a specific structural cause. Most cases settle with staying active and gradually rebuilding trunk and hip strength.',array['Numbness around the groin or saddle area, or changes to bladder or bowel control (seek urgent care)','Weakness in the legs that is getting worse','Pain spreading below the knee with pins and needles or numbness','Severe night pain, fever, unexplained weight loss or a history of cancer','Pain after a significant fall or accident']::text[],'A commonly used pain-monitoring guide (confirm with your medical professional): pain up to 3/10 during exercise is acceptable if it settles within 24 hours and morning symptoms are no worse the next day. If pain goes above 3/10, or is worse the next morning, drop back to the previous step. Staying active helps. Avoid bed rest.','4–12 weeks','Not medical advice. This section shares general considerations and example exercises commonly used for running injuries. It is not a diagnosis or a treatment plan. Always follow the advice of your doctor, physiotherapist or other medical professional, who can assess you individually. If you''re unsure about anything, check with them first.',array['Side plank 60 s each side','Hip hinge and single-leg work at full training loads pain-free','Full training including heavy lifting, sleds and carries pain-free']::text[],'If symptoms persist beyond 6 weeks despite completing the program, or keep coming back, consider getting assessed by a physio or doctor.',false,'{}'::text[],array['Which findings should trigger referral for assessment of SIJ versus lumbar sources?','Confirm healing-stage labels and the move → volume → speed focus for each phase.','Confirm tempo prescriptions and the proprioception progression placement.']::text[],'Overuse');

insert into public.rehab_phases (program_id,phase_no,name,typical_duration,goal,entry_criteria,exit_criteria,frequency,running_guidance,healing_stage,training_focus) values
('mtss',1,'Settle and load','1–2 weeks','Reduce irritation while keeping the calf and shin working.','Diffuse pain along the inner shin; walking comfortable.','Pain-free walking and daily activity; 20 single-leg calf raises each side at pain ≤2/10; 10 single-leg hops each side at pain ≤2/10.','Daily isometrics; strength every second day','A common approach: reduce running by about 50%, or replace with bike or pool running if pain is above 3/10.','Proliferative','Move'),
('mtss',2,'Build capacity','2–4 weeks','Rebuild calf, soleus and shin strength and start low-level impact.','Phase 1 exit criteria met.','25 single-leg calf raises each side; pogo hops 3 × 20 pain-free; 30 min continuous easy run at pain ≤2/10 and no worse the next morning.','Strength 3 × per week','A common approach: start the Standard return-to-run plan.','Proliferative','Volume and load capacity'),
('mtss',3,'Return to run and impact','3–6 weeks','Restore running volume and reactive strength.','Phase 2 exit criteria met.','Back to pre-injury running volume with no symptoms for 2 weeks.','Strength 2–3 × per week; plyometrics 2 × per week','A common approach: progress one variable at a time (days, then duration, then intensity) after a symptom-free week; vary surfaces; a 5% cadence increase can help.','Remodelling','Speed and power'),
('pfps',1,'Calm and activate','1–2 weeks','Settle the knee and switch on the quads and hips.','Front-of-knee pain; able to walk normally.','Stairs at pain ≤2/10; wall sit 45 s at a comfortable depth at pain ≤2/10.','Isometrics daily; hip work every second day','A common approach: keep running flat and shorter, below the distance that brings on pain; avoid downhill; raise cadence by 5–10%.','Proliferative','Move'),
('pfps',2,'Build strength','3–6 weeks','Load the quads and hips through a comfortable range.','Phase 1 exit criteria met.','10 single-leg squats to a box with good knee control; 30 min run at pain ≤2/10.','3 × per week','A common approach: start the Standard return-to-run plan if you stopped, or build steadily if still running.','Proliferative','Volume and load capacity'),
('pfps',3,'Return to full load','3–6 weeks','Heavier single-leg strength, landing control, then hills and downhills.','Phase 2 exit criteria met.','Stairs, squats, downhill running and full training pain-free.','2–3 × per week','A common approach: reintroduce hills, downhills and speed one at a time.','Remodelling','Speed and power'),
('bsi',1,'Protect and cross-train','As prescribed (often 2–6 weeks)','Let the bone heal while keeping fitness and strength.','Diagnosed low-risk bone stress injury; medical plan in place.','Pain-free walking for 30–45 min on several days in a row; no bone tenderness when pressed; medical clearance to start loading.','Cross-training 4–6 × per week; strength 2–3 × per week','A common approach: no running. Pool running, bike or swimming only if pain-free.','Protection (bone healing)','Protect and move'),
('bsi',2,'Load the bone','2–4 weeks','Build calf and leg strength and walking tolerance before any impact.','Phase 1 exit criteria met.','45 min brisk walk pain-free; 20 single-leg calf raises each side pain-free; 10 single-leg hops each side at 0/10 pain.','Strength 3 × per week','A common approach: no running yet. Walk daily.','Proliferative','Volume and load capacity'),
('bsi',3,'Return to run','6–10 weeks','Rebuild running on alternate days with no bone pain.','Phase 2 exit criteria met and medical clearance to run.','30 min continuous easy running on alternate days for 2 weeks with 0/10 bone pain.','Running every second day; strength 2–3 × per week','A common approach: follow the Bone stress return-to-run plan on flat, soft surfaces. No speed work or hills.','Remodelling','Speed and power'),
('bsi',4,'Return to full training','4–8 weeks','Rebuild volume, then add speed, hills and race-specific work.','Phase 3 exit criteria met.','Back to full training with no bone pain.','Normal training','A common approach: add days before distance, and distance before speed; one change per week.','Remodelling','Speed and power'),
('achilles_mid',1,'Isometrics and load management','1–2 weeks','Reduce pain and keep the tendon loaded.','Achilles pain and morning stiffness.','Morning stiffness settling; 20 double-leg calf raises at pain ≤3/10.','Isometrics daily, can be done before runs','A common approach: keep running if pain stays ≤3/10 and morning stiffness isn''t worsening. Remove hills and speed.','Proliferative','Move'),
('achilles_mid',2,'Heavy slow resistance','6–12 weeks','Rebuild tendon capacity with heavy, slow calf work.','Phase 1 exit criteria met.','25 single-leg calf raises each side, within 10% of the other leg; weighted single-leg calf raise 3 × 8.','3 × per week (48 h between sessions)','A common approach: build back to normal easy volume. Keep hills and speed out.','Proliferative','Volume and load capacity'),
('achilles_mid',3,'Energy storage and return','4–8 weeks','Restore springiness for fast running, hills and jumping.','Phase 2 exit criteria met.','Full training including speed and hills with stable morning symptoms.','Plyometrics 2 × per week; heavy calf work 2 × per week','A common approach: add hills, then strides, then speed sessions, one per week.','Remodelling','Speed and power'),
('achilles_ins',1,'Settle and isometrics','1–2 weeks','Reduce compression on the insertion and keep the tendon loaded.','Pain at the back of the heel where the tendon attaches.','Morning stiffness settling; 20 double-leg calf raises on flat ground at pain ≤3/10.','Isometrics daily','A common approach: keep running if pain stays ≤3/10 and isn''t worse the next morning. Avoid hills, barefoot and very flat shoes; a small heel raise can help short term. Avoid calf stretching.','Proliferative','Move'),
('achilles_ins',2,'Heavy slow resistance on flat ground','6–12 weeks','Rebuild tendon capacity without dropping the heel below flat.','Phase 1 exit criteria met.','25 single-leg calf raises each side on flat ground; weighted 3 × 8.','3 × per week (48 h between sessions)','A common approach: build back to normal flat volume. No hills yet.','Proliferative','Volume and load capacity'),
('achilles_ins',3,'Range, energy storage and return','4–8 weeks','Gradually reintroduce range, spring and hills.','Phase 2 exit criteria met.','Full training including hills and speed with stable morning symptoms.','Plyometrics 2 × per week; heavy calf work 2 × per week','A common approach: add strides, then speed, then hills last. Uphill running loads the insertion most.','Remodelling','Speed and power'),
('plantar',1,'Settle','1–2 weeks','Reduce morning pain and daily irritation.','Heel pain, worse with first steps.','First-step pain ≤3/10; walking 30 min comfortable.','Stretches daily (especially before getting out of bed); strength every second day','A common approach: reduce volume; stick to supportive shoes and flatter, softer routes.','Proliferative','Move'),
('plantar',2,'Strength','6–12 weeks','Strengthen the plantar fascia, foot and calf.','Phase 1 exit criteria met.','12 slow single-leg heel raises with the toes elevated, carrying load, at pain ≤2/10; first steps pain-free.','Every second day','A common approach: build back to normal easy volume.','Proliferative','Volume and load capacity'),
('plantar',3,'Return to full load','4–6 weeks','Add impact and speed.','Phase 2 exit criteria met.','Full training with no morning pain.','2–3 × per week','A common approach: add strides, hills and speed one at a time.','Remodelling','Speed and power'),
('itbs',1,'Settle and activate','1–2 weeks','Stay below pain onset while switching on the hip muscles.','Outside-of-knee pain that comes on during runs.','30 min flat run without pain onset.','Hip work daily or every second day','A common approach: keep runs shorter than the point where pain starts. Avoid downhills and cambered roads. Raise cadence by 5–10%.','Proliferative','Move'),
('itbs',2,'Hip strength and control','3–4 weeks','Build hip strength in standing and single-leg positions.','Phase 1 exit criteria met.','45 min run including some gentle downhills, pain-free.','3 × per week','A common approach: build volume steadily; reintroduce gentle downhills.','Proliferative','Volume and load capacity'),
('itbs',3,'Return to full load','2–4 weeks','Heavier strength and lateral power.','Phase 2 exit criteria met.','Full training including long runs and downhills pain-free.','2 × per week','A common approach: back to normal training; add long runs and downhills gradually.','Remodelling','Speed and power'),
('calf',1,'Protect and restore walking','Days 1–7','Inflammatory phase: commonly protect the tissue with relative rest and elevation, letting pain guide gentle movement.','Calf strain; able to walk.','Normal walking pain-free; 15 double-leg calf raises at pain ≤2/10.','Daily','A common approach: no running. Rest, elevate and walk only as pain allows; easy bike if pain-free.','Inflammatory','Move'),
('calf',2,'Strength','1–3 weeks','Rebuild calf strength in both straight and bent knee.','Phase 1 exit criteria met.','25 single-leg calf raises each side, within 10% of the other leg; 10 single-leg hops each side pain-free.','Every second day','A common approach: start the Standard return-to-run plan once exit criteria are met.','Proliferative','Volume and load capacity'),
('calf',3,'Return to run','2–4 weeks','Rebuild running, then elastic strength.','Phase 2 exit criteria met.','30 min run plus strides pain-free.','Running every second day to start','A common approach: follow the Standard return-to-run plan. Strides only after 20 min continuous is comfortable.','Remodelling','Speed and power'),
('calf',4,'Speed, hills and sleds','2–4 weeks','Return to fast running and sled work.','Phase 3 exit criteria met.','Full training including speed, hills and sled push.','Normal training','A common approach: add hills, then speed. Reintroduce sled push at light loads first.','Remodelling','Speed and power'),
('pht',1,'Isometrics and offload','1–3 weeks','Reduce pain and load the tendon in positions with little hip bend.','Sit-bone pain.','Sitting 30 min at pain ≤2/10; bridge holds pain-free.','Isometrics daily','A common approach: flat, easy running only if pain ≤3/10; no hills or speed.','Proliferative','Move'),
('pht',2,'Strength, increasing hip bend','4–8 weeks','Rebuild hamstring strength and gradually add hip flexion.','Phase 1 exit criteria met.','Single-leg bridge 20 reps each side; RDL 3 × 8 at a moderate load pain-free.','3 × per week','A common approach: build easy flat volume. No hills yet: uphill running significantly increases hamstring load.','Proliferative','Volume and load capacity'),
('pht',3,'Speed and power','4–6 weeks','Prepare for fast running and hills.','Phase 2 exit criteria met.','Speed, hills and full training pain-free.','2 × per week','A common approach: add flat strides first, then flat speed. Introduce short, gentle hills last and build them gradually.','Remodelling','Speed and power'),
('lbp',1,'Calm and move','1–2 weeks','Keep moving comfortably and restore easy movement.','Back, SIJ or hip pain; able to walk.','Walk 30 min comfortably; daily tasks at pain ≤3/10.','Daily','A common approach: walking daily. Easy running only if pain ≤3/10 and not worse afterwards.','Proliferative','Move'),
('lbp',2,'Strength and control','3–6 weeks','Build trunk and hip strength in standing positions.','Phase 1 exit criteria met.','Hip hinge and single-leg work at moderate load pain-free; 30 min run comfortable.','3 × per week','A common approach: build back to normal easy volume.','Proliferative','Volume and load capacity'),
('lbp',3,'Return to full load','3–6 weeks','Heavy lifting, carries, rotation and race work.','Phase 2 exit criteria met.','Full training including heavy lifting, sleds and carries pain-free.','2–3 × per week','A common approach: normal training.','Remodelling','Speed and power');

insert into public.rehab_phase_exercises (program_id,phase_no,sort_order,exercise_id,dose,notes,tempo) values
('mtss',1,1,'EX0499','5 × 45 s, 70% effort','Straight knee','Hold'),
('mtss',1,2,'EX0500','5 × 45 s','Bent knee, loaded through the knee','Hold'),
('mtss',1,3,'EX0015','3 × 15',null,'3-1-3-1'),
('mtss',1,4,'EX0508','3 × 20 m',null,null),
('mtss',1,5,'EX0505','3 × 10 × 5 s hold',null,'Hold'),
('mtss',1,6,'EX0325','3 × 30 s each side, eyes open → eyes closed','Proprioception steps 1–2. Start with the better side.',null),
('mtss',1,7,'EX0517','3 × 15 each side',null,'3-1-3-1'),
('mtss',2,1,'EX0005','3 × 15 → add load to 3 × 10','Slow, full range','3-1-3-1'),
('mtss',2,2,'EX0056','3 × 12, heavy',null,'3-1-3-1'),
('mtss',2,3,'EX0015','3 × 15, add load',null,'3-1-3-1'),
('mtss',2,4,'EX0029','3 × 15',null,'3-1-3-1'),
('mtss',2,5,'EX0025','3 × 10 each side',null,'4-0-C-0'),
('mtss',2,6,'EX0008','3 × 15',null,'3-1-3-1'),
('mtss',2,7,'EX0009','3 × 20, low and quick','Soft surface first',null),
('mtss',2,8,'EX0524','3 × 6 each side','Proprioception step 3: dynamic, eyes open',null),
('mtss',2,9,'EX0007','3 × 8 each side','Gait strength: hamstrings and glute max','3-1-3-1'),
('mtss',2,10,'EX0527','3 × 12 each side','Gait strength: adductor magnus','3-1-3-1'),
('mtss',2,11,'EX0231','3 × 30 m each side','Gait strength: obliques',null),
('mtss',3,1,'EX0050','4 × 6–8 heavy',null,'3-1-C-1'),
('mtss',3,2,'EX0056','4 × 8 heavy',null,'3-1-C-1'),
('mtss',3,3,'EX0509','3 × 15 each side',null,null),
('mtss',3,4,'EX0510','3 × 20',null,null),
('mtss',3,5,'EX0039','3 × 20 m',null,null),
('mtss',3,6,'EX0038','3 × 8 each side',null,'3-1-C-1'),
('mtss',3,7,'EX0525','3 × 5 each side','Proprioception steps 4–5: eyes closed after landing, then throughout',null),
('pfps',1,1,'EX0511','5 × 45 s','Pain-relieving isometric','Hold'),
('pfps',1,2,'EX0513','3 × 10 × 5 s',null,'Hold'),
('pfps',1,3,'EX0514','3 × 15',null,'3-1-3-1'),
('pfps',1,4,'EX0516','3 × 15 each side',null,'3-1-3-1'),
('pfps',1,5,'EX0517','3 × 15 each side',null,'3-1-3-1'),
('pfps',1,6,'EX0008','3 × 15',null,'3-1-3-1'),
('pfps',1,7,'EX0518','5 × 30 s each side',null,'Hold'),
('pfps',1,8,'EX0325','3 × 30 s each side, eyes open → eyes closed','Proprioception steps 1–2. Start with the better side.',null),
('pfps',2,1,'EX0204','3 × 10','Comfortable depth','3-1-3-1'),
('pfps',2,2,'EX0137','3 × 10–12','Limit depth if painful','3-1-3-1'),
('pfps',2,3,'EX0022','3 × 10 each side',null,'3-1-3-1'),
('pfps',2,4,'EX0515','3 × 10 each side','Knee tracks over the toes','3-1-3-1'),
('pfps',2,5,'EX0024','3 × 12 each side',null,'3-1-3-1'),
('pfps',2,6,'EX0519','3 × 10 m',null,null),
('pfps',2,7,'EX0520','3 × 12 each side',null,'3-1-3-1'),
('pfps',2,8,'EX0091','3 × 10',null,'3-1-3-1'),
('pfps',2,9,'EX0524','3 × 6 each side','Proprioception step 3: dynamic, eyes open',null),
('pfps',2,10,'EX0007','3 × 8 each side','Gait strength: hamstrings and glute max','3-1-3-1'),
('pfps',2,11,'EX0527','3 × 12 each side','Gait strength: adductor magnus','3-1-3-1'),
('pfps',2,12,'EX0231','3 × 30 m each side','Gait strength: obliques',null),
('pfps',3,1,'EX0038','3 × 8 each side',null,'3-1-C-1'),
('pfps',3,2,'EX0472','3 × 8 each side',null,'3-1-C-1'),
('pfps',3,3,'EX0021','3 × 10 each side',null,'3-1-C-1'),
('pfps',3,4,'EX0144','4 × 6–8',null,'3-1-C-1'),
('pfps',3,5,'EX0009','3 × 20',null,null),
('pfps',3,6,'EX0326','3 × 5 each side',null,null),
('pfps',3,7,'EX0053','3 × 5','Step down',null),
('pfps',3,8,'EX0525','3 × 5 each side','Proprioception steps 4–5: eyes closed after landing, then throughout',null),
('bsi',1,1,'EX0030','20–40 min easy to moderate',null,null),
('bsi',1,2,'EX0012','20–40 min','Only if pain-free',null),
('bsi',1,3,'EX0497','As prescribed, pain-free',null,null),
('bsi',1,4,'EX0008','3 × 15',null,'3-1-3-1'),
('bsi',1,5,'EX0517','3 × 15 each side',null,'3-1-3-1'),
('bsi',1,6,'EX0010','3 × 10',null,null),
('bsi',1,7,'EX0131','3 × 10 each side','Upper body and core work keep going','3-1-3-1'),
('bsi',2,1,'EX0061','3 × 15 double-leg → single-leg',null,'3-1-3-1'),
('bsi',2,2,'EX0056','3 × 12',null,'3-1-3-1'),
('bsi',2,3,'EX0015','3 × 15',null,'3-1-3-1'),
('bsi',2,4,'EX0325','3 × 30 s each side',null,null),
('bsi',2,5,'EX0006','3 × 10 each side',null,'3-1-3-1'),
('bsi',2,6,'EX0022','3 × 10 each side',null,'3-1-3-1'),
('bsi',2,7,'EX0497','30–45 min daily',null,null),
('bsi',2,8,'EX0524','3 × 6 each side','Proprioception step 3: dynamic, eyes open',null),
('bsi',2,9,'EX0007','3 × 8 each side','Gait strength: hamstrings and glute max','3-1-3-1'),
('bsi',2,10,'EX0527','3 × 12 each side','Gait strength: adductor magnus','3-1-3-1'),
('bsi',2,11,'EX0231','3 × 30 m each side','Gait strength: obliques',null),
('bsi',3,1,'EX0005','3 × 15, add load',null,'3-1-C-1'),
('bsi',3,2,'EX0056','3 × 10 heavy',null,'3-1-C-1'),
('bsi',3,3,'EX0009','3 × 20, low','Add only when pain-free',null),
('bsi',3,4,'EX0510','2 × 20',null,null),
('bsi',3,5,'EX0038','3 × 8 each side',null,'3-1-C-1'),
('bsi',3,6,'EX0525','3 × 5 each side','Proprioception steps 4–5: eyes closed after landing, then throughout',null),
('bsi',4,1,'EX0050','4 × 6–8 heavy',null,'3-1-C-1'),
('bsi',4,2,'EX0509','3 × 15 each side',null,null),
('bsi',4,3,'EX0039','3 × 20 m',null,null),
('bsi',4,4,'EX0003','6 × 20 s','After easy runs',null),
('bsi',4,5,'EX0525','3 × 5 each side','Proprioception steps 4–5: eyes closed after landing, then throughout',null),
('achilles_mid',1,1,'EX0499','5 × 45 s, 70% effort',null,'Hold'),
('achilles_mid',1,2,'EX0500','5 × 45 s',null,'Hold'),
('achilles_mid',1,3,'EX0061','3 × 15 double-leg, slow',null,'3-1-3-1'),
('achilles_mid',1,4,'EX0008','3 × 15',null,'3-1-3-1'),
('achilles_mid',1,5,'EX0325','3 × 30 s each side, eyes open → eyes closed','Proprioception steps 1–2. Start with the better side.',null),
('achilles_mid',2,1,'EX0005','3 × 15 → weighted 3 × 8','3 s up, 3 s down','3-1-3-1'),
('achilles_mid',2,2,'EX0056','3 × 8–12 heavy',null,'3-1-3-1'),
('achilles_mid',2,3,'EX0214','3 × 8–12 heavy',null,'3-1-3-1'),
('achilles_mid',2,4,'EX0501','3 × 15',null,'4-0-C-0'),
('achilles_mid',2,5,'EX0502','3 × 15',null,'4-0-C-0'),
('achilles_mid',2,6,'EX0524','3 × 6 each side','Proprioception step 3: dynamic, eyes open',null),
('achilles_mid',2,7,'EX0007','3 × 8 each side','Gait strength: hamstrings and glute max','3-1-3-1'),
('achilles_mid',2,8,'EX0527','3 × 12 each side','Gait strength: adductor magnus','3-1-3-1'),
('achilles_mid',2,9,'EX0231','3 × 30 m each side','Gait strength: obliques',null),
('achilles_mid',3,1,'EX0009','3 × 20',null,null),
('achilles_mid',3,2,'EX0013','3 × 1 min',null,null),
('achilles_mid',3,3,'EX0510','3 × 20',null,null),
('achilles_mid',3,4,'EX0509','3 × 15 each side',null,null),
('achilles_mid',3,5,'EX0039','3 × 20 m',null,null),
('achilles_mid',3,6,'EX0050','3 × 6–8 heavy','Maintenance','3-1-C-1'),
('achilles_mid',3,7,'EX0525','3 × 5 each side','Proprioception steps 4–5: eyes closed after landing, then throughout',null),
('achilles_ins',1,1,'EX0499','5 × 45 s, 70% effort','Heel stays above floor level','Hold'),
('achilles_ins',1,2,'EX0500','5 × 45 s',null,'Hold'),
('achilles_ins',1,3,'EX0061','3 × 15 double-leg on flat ground',null,'3-1-3-1'),
('achilles_ins',1,4,'EX0008','3 × 15',null,'3-1-3-1'),
('achilles_ins',1,5,'EX0325','3 × 30 s each side, eyes open → eyes closed','Proprioception steps 1–2. Start with the better side.',null),
('achilles_ins',2,1,'EX0005','3 × 15 → weighted 3 × 8','On flat ground, 3 s up, 3 s down','3-1-3-1'),
('achilles_ins',2,2,'EX0056','3 × 8–12 heavy',null,'3-1-3-1'),
('achilles_ins',2,3,'EX0214','3 × 8–12 heavy','Don''t let the heel drop past neutral','3-1-3-1'),
('achilles_ins',2,4,'EX0524','3 × 6 each side','Proprioception step 3: dynamic, eyes open',null),
('achilles_ins',2,5,'EX0007','3 × 8 each side','Gait strength: hamstrings and glute max','3-1-3-1'),
('achilles_ins',2,6,'EX0527','3 × 12 each side','Gait strength: adductor magnus','3-1-3-1'),
('achilles_ins',2,7,'EX0231','3 × 30 m each side','Gait strength: obliques',null),
('achilles_ins',3,1,'EX0501','3 × 12, only to slightly below flat','Introduce range gradually if pain-free','4-0-C-0'),
('achilles_ins',3,2,'EX0009','3 × 20',null,null),
('achilles_ins',3,3,'EX0013','3 × 1 min',null,null),
('achilles_ins',3,4,'EX0509','3 × 15 each side',null,null),
('achilles_ins',3,5,'EX0050','3 × 6–8 heavy','Maintenance','3-1-C-1'),
('achilles_ins',3,6,'EX0525','3 × 5 each side','Proprioception steps 4–5: eyes closed after landing, then throughout',null),
('plantar',1,1,'EX0495','3 × 30 s before first steps',null,null),
('plantar',1,2,'EX0490','3 × 30 s each side',null,null),
('plantar',1,3,'EX0496','2 min',null,null),
('plantar',1,4,'EX0505','3 × 10 × 5 s hold',null,'Hold'),
('plantar',1,5,'EX0504','3 × 20',null,'3-1-3-1'),
('plantar',1,6,'EX0499','5 × 45 s',null,'Hold'),
('plantar',1,7,'EX0325','3 × 30 s each side, eyes open → eyes closed','Proprioception steps 1–2. Start with the better side.',null),
('plantar',2,1,'EX0503','3 sets of 12 → 8 heavy','3 s up, 2 s hold, 3 s down; towel under the toes','3-1-3-1'),
('plantar',2,2,'EX0005','3 × 12',null,'3-1-3-1'),
('plantar',2,3,'EX0056','3 × 12',null,'3-1-3-1'),
('plantar',2,4,'EX0506','3 × 10',null,'3-1-3-1'),
('plantar',2,5,'EX0325','3 × 30 s each side',null,null),
('plantar',2,6,'EX0524','3 × 6 each side','Proprioception step 3: dynamic, eyes open',null),
('plantar',2,7,'EX0007','3 × 8 each side','Gait strength: hamstrings and glute max','3-1-3-1'),
('plantar',2,8,'EX0527','3 × 12 each side','Gait strength: adductor magnus','3-1-3-1'),
('plantar',2,9,'EX0231','3 × 30 m each side','Gait strength: obliques',null),
('plantar',3,1,'EX0009','3 × 20',null,null),
('plantar',3,2,'EX0013','3 × 1 min',null,null),
('plantar',3,3,'EX0503','2 × 8 heavy','Maintenance','3-1-C-1'),
('plantar',3,4,'EX0509','3 × 10 each side',null,null),
('plantar',3,5,'EX0525','3 × 5 each side','Proprioception steps 4–5: eyes closed after landing, then throughout',null),
('itbs',1,1,'EX0518','5 × 30 s each side',null,'Hold'),
('itbs',1,2,'EX0517','3 × 15 each side',null,'3-1-3-1'),
('itbs',1,3,'EX0516','3 × 15 each side',null,'3-1-3-1'),
('itbs',1,4,'EX0008','3 × 15',null,'3-1-3-1'),
('itbs',1,5,'EX0494','2–3 min, outside of thigh and glutes','For comfort only',null),
('itbs',1,6,'EX0325','3 × 30 s each side, eyes open → eyes closed','Proprioception steps 1–2. Start with the better side.',null),
('itbs',2,1,'EX0479','3 × 10 each side',null,'Hold'),
('itbs',2,2,'EX0519','3 × 10 m',null,null),
('itbs',2,3,'EX0520','3 × 12 each side',null,'3-1-3-1'),
('itbs',2,4,'EX0007','3 × 10 each side',null,'3-1-3-1'),
('itbs',2,5,'EX0515','3 × 10 each side',null,'3-1-3-1'),
('itbs',2,6,'EX0022','3 × 10 each side',null,'3-1-3-1'),
('itbs',2,7,'EX0524','3 × 6 each side','Proprioception step 3: dynamic, eyes open',null),
('itbs',2,8,'EX0527','3 × 12 each side','Gait strength: adductor magnus','3-1-3-1'),
('itbs',2,9,'EX0231','3 × 30 m each side','Gait strength: obliques',null),
('itbs',3,1,'EX0038','3 × 8 each side',null,'3-1-C-1'),
('itbs',3,2,'EX0052','3 × 8',null,'3-1-C-1'),
('itbs',3,3,'EX0054','3 × 8 each side',null,null),
('itbs',3,4,'EX0509','3 × 15 each side',null,null),
('itbs',3,5,'EX0525','3 × 5 each side','Proprioception steps 4–5: eyes closed after landing, then throughout',null),
('calf',1,1,'EX0499','5 × 30 s, gentle',null,'Hold'),
('calf',1,2,'EX0028','2 × 10',null,null),
('calf',1,3,'EX0012','15–20 min easy',null,null),
('calf',1,4,'EX0497','10–30 min',null,null),
('calf',1,5,'EX0325','3 × 30 s each side, eyes open → eyes closed','Proprioception steps 1–2. Start with the better side.',null),
('calf',2,1,'EX0061','3 × 15 → single-leg',null,'3-1-3-1'),
('calf',2,2,'EX0056','3 × 12',null,'3-1-3-1'),
('calf',2,3,'EX0029','3 × 15',null,'3-1-3-1'),
('calf',2,4,'EX0501','3 × 12',null,'4-0-C-0'),
('calf',2,5,'EX0214','3 × 10',null,'3-1-3-1'),
('calf',2,6,'EX0524','3 × 6 each side','Proprioception step 3: dynamic, eyes open',null),
('calf',2,7,'EX0007','3 × 8 each side','Gait strength: hamstrings and glute max','3-1-3-1'),
('calf',2,8,'EX0527','3 × 12 each side','Gait strength: adductor magnus','3-1-3-1'),
('calf',2,9,'EX0231','3 × 30 m each side','Gait strength: obliques',null),
('calf',3,1,'EX0009','3 × 20',null,null),
('calf',3,2,'EX0013','3 × 1 min',null,null),
('calf',3,3,'EX0005','3 × 10 weighted',null,'3-1-C-1'),
('calf',3,4,'EX0003','4–6 × 20 s',null,null),
('calf',3,5,'EX0525','3 × 5 each side','Proprioception steps 4–5: eyes closed after landing, then throughout',null),
('calf',4,1,'EX0509','3 × 15 each side',null,null),
('calf',4,2,'EX0039','3 × 20 m',null,null),
('calf',4,3,'EX0195','4 × 20 m light → race weight',null,null),
('calf',4,4,'EX0050','3 × 6–8 heavy',null,'3-1-C-1'),
('calf',4,5,'EX0525','3 × 5 each side','Proprioception steps 4–5: eyes closed after landing, then throughout',null),
('pht',1,1,'EX0522','5 × 30–45 s',null,'Hold'),
('pht',1,2,'EX0521','5 × 30 s',null,'Hold'),
('pht',1,3,'EX0008','3 × 15',null,'3-1-3-1'),
('pht',1,4,'EX0010','3 × 10',null,null),
('pht',1,5,'EX0325','3 × 30 s each side, eyes open → eyes closed','Proprioception steps 1–2. Start with the better side.',null),
('pht',2,1,'EX0024','3 × 12 each side',null,'3-1-3-1'),
('pht',2,2,'EX0465','3 × 10',null,'3-1-3-1'),
('pht',2,3,'EX0467','3 × 8',null,'3-1-3-1'),
('pht',2,4,'EX0052','3 × 10',null,'3-1-3-1'),
('pht',2,5,'EX0091','3 × 8','Start with a short range, then go deeper','3-1-3-1'),
('pht',2,6,'EX0145','3 × 10',null,'3-1-3-1'),
('pht',2,7,'EX0524','3 × 6 each side','Proprioception step 3: dynamic, eyes open',null),
('pht',2,8,'EX0007','3 × 8 each side','Gait strength: hamstrings and glute max','3-1-3-1'),
('pht',2,9,'EX0527','3 × 12 each side','Gait strength: adductor magnus','3-1-3-1'),
('pht',2,10,'EX0231','3 × 30 m each side','Gait strength: obliques',null),
('pht',3,1,'EX0040','3 × 5',null,'3-1-C-1'),
('pht',3,2,'EX0007','3 × 8 each side',null,'3-1-C-1'),
('pht',3,3,'EX0077','3 × 15',null,null),
('pht',3,4,'EX0003','6 × 20 s',null,null),
('pht',3,5,'EX0067','4–6 × 8–10 s, gentle gradient','Last to be added, after flat speed is comfortable',null),
('pht',3,6,'EX0525','3 × 5 each side','Proprioception steps 4–5: eyes closed after landing, then throughout',null),
('lbp',1,1,'EX0497','20–30 min',null,null),
('lbp',1,2,'EX0435','2 × 10',null,null),
('lbp',1,3,'EX0482','2 × 10',null,null),
('lbp',1,4,'EX0492','3 × 30 s',null,null),
('lbp',1,5,'EX0493','2 × 10','Only if it eases symptoms',null),
('lbp',1,6,'EX0484','3 min',null,null),
('lbp',1,7,'EX0480','3 × 8 × 10 s hold',null,'Hold'),
('lbp',1,8,'EX0481','3 × 15 s each side',null,'Hold'),
('lbp',1,9,'EX0026','3 × 8 each side',null,null),
('lbp',1,10,'EX0485','2 × 10',null,null),
('lbp',2,1,'EX0010','3 × 10',null,null),
('lbp',2,2,'EX0017','3 × 30 s each side',null,'Hold'),
('lbp',2,3,'EX0027','3 × 10 each side',null,'3-1-3-1'),
('lbp',2,4,'EX0231','3 × 30 m each side',null,null),
('lbp',2,5,'EX0082','2 × 10',null,'3-1-3-1'),
('lbp',2,6,'EX0091','3 × 10 light',null,'3-1-3-1'),
('lbp',2,7,'EX0052','3 × 10',null,'3-1-3-1'),
('lbp',2,8,'EX0006','3 × 10 each side',null,'3-1-3-1'),
('lbp',2,9,'EX0018','3 × 15 s each side','For SIJ and groin','Hold'),
('lbp',2,10,'EX0157','3 × 10 m',null,null),
('lbp',2,11,'EX0007','3 × 8 each side','Gait strength: hamstrings and glute max','3-1-3-1'),
('lbp',2,12,'EX0527','3 × 12 each side','Gait strength: adductor magnus','3-1-3-1'),
('lbp',3,1,'EX0139','4 × 5',null,'3-1-C-1'),
('lbp',3,2,'EX0077','3 × 15',null,null),
('lbp',3,3,'EX0243','4 × 40 m heavy',null,null),
('lbp',3,4,'EX0342','3 × 8 each side',null,'3-1-C-1'),
('lbp',3,5,'EX0007','3 × 8 each side',null,'3-1-C-1'),
('lbp',3,6,'EX0195','4 × 20 m',null,null);

insert into public.return_to_run_plans (id,name,prerequisites,progression_rule) values
('standard','Standard return-to-run plan','30 min brisk walk pain-free; 10 single-leg hops each side at pain ≤2/10.','Run every second day. Do each step twice. Move up when pain stays ≤2/10 during the run and is no worse the next morning. If pain rises, drop back one step. After the final step, build running one variable at a time: add days first, then duration, then intensity (hills, speed). Only progress after a week with no increase in symptoms. Hold if symptoms sit at 2–3/10; drop back if they go higher.'),
('bone','Bone stress return-to-run plan','Medical clearance; 45 min brisk walk pain-free on several days; 10 single-leg hops each side at 0/10; no bone tenderness when pressed.','Only with medical clearance. Run every second day on flat, soft surfaces. Do each step 2–3 times. Move up only with 0/10 bone pain during and for 24 hours after. Any bone pain: stop and drop back one step. No speed or hills until 30 min continuous has been comfortable for 2 weeks. After the final step, build one variable at a time with the treating clinician''s guidance.');

insert into public.return_to_run_steps (plan_id,step,run_walk,repeats,total_min) values
('standard',1,'1 min run / 1 min walk','× 10',20),
('standard',2,'2 min run / 1 min walk','× 7',21),
('standard',3,'3 min run / 1 min walk','× 5',20),
('standard',4,'4 min run / 1 min walk','× 5',25),
('standard',5,'5 min run / 1 min walk','× 4',24),
('standard',6,'8 min run / 1 min walk','× 3',27),
('standard',7,'10 min run / 1 min walk','× 3',33),
('standard',8,'15 min run / 1 min walk','× 2',32),
('standard',9,'20 min continuous',null,20),
('standard',10,'30 min continuous',null,30),
('bone',1,'1 min run / 4 min walk','× 6',30),
('bone',2,'2 min run / 3 min walk','× 6',30),
('bone',3,'3 min run / 2 min walk','× 6',30),
('bone',4,'4 min run / 1 min walk','× 6',30),
('bone',5,'5 min run / 1 min walk','× 5',30),
('bone',6,'10 min run / 1 min walk','× 3',33),
('bone',7,'15 min run / 1 min walk','× 2',32),
('bone',8,'20 min continuous',null,20),
('bone',9,'25 min continuous',null,25),
('bone',10,'30 min continuous',null,30);


insert into supabase_migrations.schema_migrations (version, name) values ('20260925030000','rehab_v4_considerations_wording')
on conflict (version) do nothing;

-- Check: should show 10 | 15
select (select count(*) from public.rehab_programs) as programs,
       (select count(*) from public.rehab_global_guidance) as guidance;

commit;
